// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/app.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class AppProto {
  private AppProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:App)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 appId = 1;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 1;</code>
     */
    int getAppId();

    /**
     * <code>optional string appName = 2;</code>
     */
    boolean hasAppName();
    /**
     * <code>optional string appName = 2;</code>
     */
    java.lang.String getAppName();
    /**
     * <code>optional string appName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>optional string dbUser = 3;</code>
     */
    boolean hasDbUser();
    /**
     * <code>optional string dbUser = 3;</code>
     */
    java.lang.String getDbUser();
    /**
     * <code>optional string dbUser = 3;</code>
     */
    com.google.protobuf.ByteString
        getDbUserBytes();

    /**
     * <code>optional string dbPwd = 4;</code>
     */
    boolean hasDbPwd();
    /**
     * <code>optional string dbPwd = 4;</code>
     */
    java.lang.String getDbPwd();
    /**
     * <code>optional string dbPwd = 4;</code>
     */
    com.google.protobuf.ByteString
        getDbPwdBytes();
  }
  /**
   * Protobuf type {@code App}
   */
  public static final class App extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:App)
      AppOrBuilder {
    // Use App.newBuilder() to construct.
    private App(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private App(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final App defaultInstance;
    public static App getDefaultInstance() {
      return defaultInstance;
    }

    public App getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private App(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dbUser_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dbPwd_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.AppProto.internal_static_App_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.AppProto.internal_static_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.AppProto.App.class, cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder.class);
    }

    public static com.google.protobuf.Parser<App> PARSER =
        new com.google.protobuf.AbstractParser<App>() {
      public App parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new App(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<App> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appId_;
    /**
     * <code>required int32 appId = 1;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 appId = 1;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int APPNAME_FIELD_NUMBER = 2;
    private java.lang.Object appName_;
    /**
     * <code>optional string appName = 2;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string appName = 2;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string appName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DBUSER_FIELD_NUMBER = 3;
    private java.lang.Object dbUser_;
    /**
     * <code>optional string dbUser = 3;</code>
     */
    public boolean hasDbUser() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string dbUser = 3;</code>
     */
    public java.lang.String getDbUser() {
      java.lang.Object ref = dbUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbUser_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dbUser = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDbUserBytes() {
      java.lang.Object ref = dbUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DBPWD_FIELD_NUMBER = 4;
    private java.lang.Object dbPwd_;
    /**
     * <code>optional string dbPwd = 4;</code>
     */
    public boolean hasDbPwd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string dbPwd = 4;</code>
     */
    public java.lang.String getDbPwd() {
      java.lang.Object ref = dbPwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbPwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dbPwd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDbPwdBytes() {
      java.lang.Object ref = dbPwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      appId_ = 0;
      appName_ = "";
      dbUser_ = "";
      dbPwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, appId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDbUserBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDbPwdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, appId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDbUserBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDbPwdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.AppProto.App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.AppProto.App prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:App)
        cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.AppProto.internal_static_App_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.AppProto.internal_static_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.AppProto.App.class, cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.AppProto.App.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dbUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dbPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.AppProto.internal_static_App_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.AppProto.App getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.AppProto.App build() {
        cc.changic.platform.etl.base.model.db.proto.AppProto.App result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.AppProto.App buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.AppProto.App result = new cc.changic.platform.etl.base.model.db.proto.AppProto.App(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dbUser_ = dbUser_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dbPwd_ = dbPwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.AppProto.App) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.AppProto.App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.AppProto.App other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance()) return this;
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasAppName()) {
          bitField0_ |= 0x00000002;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasDbUser()) {
          bitField0_ |= 0x00000004;
          dbUser_ = other.dbUser_;
          onChanged();
        }
        if (other.hasDbPwd()) {
          bitField0_ |= 0x00000008;
          dbPwd_ = other.dbPwd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.AppProto.App parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.AppProto.App) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int appId_ ;
      /**
       * <code>required int32 appId = 1;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 appId = 1;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 1;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000001;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 1;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>optional string appName = 2;</code>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string appName = 2;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string appName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appName = 2;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appName = 2;</code>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appName = 2;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dbUser_ = "";
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public boolean hasDbUser() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public java.lang.String getDbUser() {
        java.lang.Object ref = dbUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dbUser_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDbUserBytes() {
        java.lang.Object ref = dbUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public Builder setDbUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dbUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public Builder clearDbUser() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dbUser_ = getDefaultInstance().getDbUser();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbUser = 3;</code>
       */
      public Builder setDbUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dbUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dbPwd_ = "";
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public boolean hasDbPwd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public java.lang.String getDbPwd() {
        java.lang.Object ref = dbPwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dbPwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDbPwdBytes() {
        java.lang.Object ref = dbPwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public Builder setDbPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dbPwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public Builder clearDbPwd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dbPwd_ = getDefaultInstance().getDbPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbPwd = 4;</code>
       */
      public Builder setDbPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dbPwd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:App)
    }

    static {
      defaultInstance = new App(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:App)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_App_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_App_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014db/app.proto\"D\n\003App\022\r\n\005appId\030\001 \002(\005\022\017\n\007" +
      "appName\030\002 \001(\t\022\016\n\006dbUser\030\003 \001(\t\022\r\n\005dbPwd\030\004" +
      " \001(\tB7\n+cc.changic.platform.etl.base.mod" +
      "el.db.protoB\010AppProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_App_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_App_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_App_descriptor,
        new java.lang.String[] { "AppId", "AppName", "DbUser", "DbPwd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
