// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/config_version.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class ConfigVersionProto {
  private ConfigVersionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConfigVersionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConfigVersion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string modifyTime = 2;</code>
     */
    boolean hasModifyTime();
    /**
     * <code>optional string modifyTime = 2;</code>
     */
    java.lang.String getModifyTime();
    /**
     * <code>optional string modifyTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getModifyTimeBytes();

    /**
     * <code>optional int32 status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code ConfigVersion}
   */
  public static final class ConfigVersion extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ConfigVersion)
      ConfigVersionOrBuilder {
    // Use ConfigVersion.newBuilder() to construct.
    private ConfigVersion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigVersion(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigVersion defaultInstance;
    public static ConfigVersion getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigVersion getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigVersion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              modifyTime_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.internal_static_ConfigVersion_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.internal_static_ConfigVersion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.class, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigVersion> PARSER =
        new com.google.protobuf.AbstractParser<ConfigVersion>() {
      public ConfigVersion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigVersion(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigVersion> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MODIFYTIME_FIELD_NUMBER = 2;
    private java.lang.Object modifyTime_;
    /**
     * <code>optional string modifyTime = 2;</code>
     */
    public boolean hasModifyTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string modifyTime = 2;</code>
     */
    public java.lang.String getModifyTime() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modifyTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string modifyTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModifyTimeBytes() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional int32 status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      id_ = 0;
      modifyTime_ = "";
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getModifyTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getModifyTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConfigVersion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConfigVersion)
        cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.internal_static_ConfigVersion_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.internal_static_ConfigVersion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.class, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        modifyTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.internal_static_ConfigVersion_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion build() {
        cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion result = new cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modifyTime_ = modifyTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasModifyTime()) {
          bitField0_ |= 0x00000002;
          modifyTime_ = other.modifyTime_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modifyTime_ = "";
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public boolean hasModifyTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public java.lang.String getModifyTime() {
        java.lang.Object ref = modifyTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            modifyTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModifyTimeBytes() {
        java.lang.Object ref = modifyTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modifyTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public Builder setModifyTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        modifyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public Builder clearModifyTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modifyTime_ = getDefaultInstance().getModifyTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       */
      public Builder setModifyTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        modifyTime_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ConfigVersion)
    }

    static {
      defaultInstance = new ConfigVersion(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ConfigVersion)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConfigVersion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ConfigVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027db/config_version.proto\"?\n\rConfigVersi" +
      "on\022\n\n\002id\030\001 \002(\005\022\022\n\nmodifyTime\030\002 \001(\t\022\016\n\006st" +
      "atus\030\003 \001(\005BA\n+cc.changic.platform.etl.ba" +
      "se.model.db.protoB\022ConfigVersionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ConfigVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConfigVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ConfigVersion_descriptor,
        new java.lang.String[] { "Id", "ModifyTime", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
