// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/file_task.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class FileTaskProto {
  private FileTaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int32 appId = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 2;</code>
     */
    int getAppId();

    /**
     * <code>required string taskName = 3;</code>
     */
    boolean hasTaskName();
    /**
     * <code>required string taskName = 3;</code>
     */
    java.lang.String getTaskName();
    /**
     * <code>required string taskName = 3;</code>
     */
    com.google.protobuf.ByteString
        getTaskNameBytes();

    /**
     * <code>required int32 taskType = 4;</code>
     */
    boolean hasTaskType();
    /**
     * <code>required int32 taskType = 4;</code>
     */
    int getTaskType();

    /**
     * <code>required int32 nextInterval = 5;</code>
     */
    boolean hasNextInterval();
    /**
     * <code>required int32 nextInterval = 5;</code>
     */
    int getNextInterval();

    /**
     * <code>required string sourceDir = 6;</code>
     */
    boolean hasSourceDir();
    /**
     * <code>required string sourceDir = 6;</code>
     */
    java.lang.String getSourceDir();
    /**
     * <code>required string sourceDir = 6;</code>
     */
    com.google.protobuf.ByteString
        getSourceDirBytes();

    /**
     * <code>required string storageDir = 7;</code>
     */
    boolean hasStorageDir();
    /**
     * <code>required string storageDir = 7;</code>
     */
    java.lang.String getStorageDir();
    /**
     * <code>required string storageDir = 7;</code>
     */
    com.google.protobuf.ByteString
        getStorageDirBytes();

    /**
     * <code>required string fileName = 8;</code>
     */
    boolean hasFileName();
    /**
     * <code>required string fileName = 8;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>required string fileName = 8;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    boolean hasDeleteInterval();
    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    java.lang.String getDeleteInterval();
    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    com.google.protobuf.ByteString
        getDeleteIntervalBytes();

    /**
     * <code>optional int32 odsId = 10;</code>
     */
    boolean hasOdsId();
    /**
     * <code>optional int32 odsId = 10;</code>
     */
    int getOdsId();

    /**
     * <code>optional string insertSql = 11;</code>
     */
    boolean hasInsertSql();
    /**
     * <code>optional string insertSql = 11;</code>
     */
    java.lang.String getInsertSql();
    /**
     * <code>optional string insertSql = 11;</code>
     */
    com.google.protobuf.ByteString
        getInsertSqlBytes();

    /**
     * <code>optional string deleteSql = 12;</code>
     */
    boolean hasDeleteSql();
    /**
     * <code>optional string deleteSql = 12;</code>
     */
    java.lang.String getDeleteSql();
    /**
     * <code>optional string deleteSql = 12;</code>
     */
    com.google.protobuf.ByteString
        getDeleteSqlBytes();
  }
  /**
   * Protobuf type {@code FileTask}
   */
  public static final class FileTask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FileTask)
      FileTaskOrBuilder {
    // Use FileTask.newBuilder() to construct.
    private FileTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileTask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileTask defaultInstance;
    public static FileTask getDefaultInstance() {
      return defaultInstance;
    }

    public FileTask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              appId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              taskName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              taskType_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              nextInterval_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              sourceDir_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              storageDir_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              fileName_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              deleteInterval_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              odsId_ = input.readInt32();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              insertSql_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              deleteSql_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.internal_static_FileTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.internal_static_FileTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.class, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder.class);
    }

    public static com.google.protobuf.Parser<FileTask> PARSER =
        new com.google.protobuf.AbstractParser<FileTask>() {
      public FileTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileTask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileTask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>required int32 appId = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 appId = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int TASKNAME_FIELD_NUMBER = 3;
    private java.lang.Object taskName_;
    /**
     * <code>required string taskName = 3;</code>
     */
    public boolean hasTaskName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string taskName = 3;</code>
     */
    public java.lang.String getTaskName() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKTYPE_FIELD_NUMBER = 4;
    private int taskType_;
    /**
     * <code>required int32 taskType = 4;</code>
     */
    public boolean hasTaskType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 taskType = 4;</code>
     */
    public int getTaskType() {
      return taskType_;
    }

    public static final int NEXTINTERVAL_FIELD_NUMBER = 5;
    private int nextInterval_;
    /**
     * <code>required int32 nextInterval = 5;</code>
     */
    public boolean hasNextInterval() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 nextInterval = 5;</code>
     */
    public int getNextInterval() {
      return nextInterval_;
    }

    public static final int SOURCEDIR_FIELD_NUMBER = 6;
    private java.lang.Object sourceDir_;
    /**
     * <code>required string sourceDir = 6;</code>
     */
    public boolean hasSourceDir() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string sourceDir = 6;</code>
     */
    public java.lang.String getSourceDir() {
      java.lang.Object ref = sourceDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sourceDir = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDirBytes() {
      java.lang.Object ref = sourceDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORAGEDIR_FIELD_NUMBER = 7;
    private java.lang.Object storageDir_;
    /**
     * <code>required string storageDir = 7;</code>
     */
    public boolean hasStorageDir() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string storageDir = 7;</code>
     */
    public java.lang.String getStorageDir() {
      java.lang.Object ref = storageDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          storageDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string storageDir = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStorageDirBytes() {
      java.lang.Object ref = storageDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILENAME_FIELD_NUMBER = 8;
    private java.lang.Object fileName_;
    /**
     * <code>required string fileName = 8;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string fileName = 8;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETEINTERVAL_FIELD_NUMBER = 9;
    private java.lang.Object deleteInterval_;
    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    public boolean hasDeleteInterval() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    public java.lang.String getDeleteInterval() {
      java.lang.Object ref = deleteInterval_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deleteInterval_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deleteInterval = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDeleteIntervalBytes() {
      java.lang.Object ref = deleteInterval_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deleteInterval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ODSID_FIELD_NUMBER = 10;
    private int odsId_;
    /**
     * <code>optional int32 odsId = 10;</code>
     */
    public boolean hasOdsId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 odsId = 10;</code>
     */
    public int getOdsId() {
      return odsId_;
    }

    public static final int INSERTSQL_FIELD_NUMBER = 11;
    private java.lang.Object insertSql_;
    /**
     * <code>optional string insertSql = 11;</code>
     */
    public boolean hasInsertSql() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string insertSql = 11;</code>
     */
    public java.lang.String getInsertSql() {
      java.lang.Object ref = insertSql_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          insertSql_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string insertSql = 11;</code>
     */
    public com.google.protobuf.ByteString
        getInsertSqlBytes() {
      java.lang.Object ref = insertSql_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        insertSql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETESQL_FIELD_NUMBER = 12;
    private java.lang.Object deleteSql_;
    /**
     * <code>optional string deleteSql = 12;</code>
     */
    public boolean hasDeleteSql() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string deleteSql = 12;</code>
     */
    public java.lang.String getDeleteSql() {
      java.lang.Object ref = deleteSql_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deleteSql_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deleteSql = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDeleteSqlBytes() {
      java.lang.Object ref = deleteSql_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deleteSql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      appId_ = 0;
      taskName_ = "";
      taskType_ = 0;
      nextInterval_ = 0;
      sourceDir_ = "";
      storageDir_ = "";
      fileName_ = "";
      deleteInterval_ = "";
      odsId_ = 0;
      insertSql_ = "";
      deleteSql_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextInterval()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSourceDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStorageDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTaskNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, taskType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, nextInterval_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSourceDirBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getStorageDirBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getDeleteIntervalBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, odsId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getInsertSqlBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getDeleteSqlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTaskNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, taskType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, nextInterval_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSourceDirBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getStorageDirBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getDeleteIntervalBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, odsId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getInsertSqlBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getDeleteSqlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileTask)
        cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.internal_static_FileTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.internal_static_FileTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.class, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        taskName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        taskType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        nextInterval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        storageDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        deleteInterval_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        odsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        insertSql_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        deleteSql_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.internal_static_FileTask_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask build() {
        cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask result = new cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taskName_ = taskName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskType_ = taskType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nextInterval_ = nextInterval_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourceDir_ = sourceDir_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.storageDir_ = storageDir_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.deleteInterval_ = deleteInterval_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.odsId_ = odsId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.insertSql_ = insertSql_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.deleteSql_ = deleteSql_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasTaskName()) {
          bitField0_ |= 0x00000004;
          taskName_ = other.taskName_;
          onChanged();
        }
        if (other.hasTaskType()) {
          setTaskType(other.getTaskType());
        }
        if (other.hasNextInterval()) {
          setNextInterval(other.getNextInterval());
        }
        if (other.hasSourceDir()) {
          bitField0_ |= 0x00000020;
          sourceDir_ = other.sourceDir_;
          onChanged();
        }
        if (other.hasStorageDir()) {
          bitField0_ |= 0x00000040;
          storageDir_ = other.storageDir_;
          onChanged();
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000080;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasDeleteInterval()) {
          bitField0_ |= 0x00000100;
          deleteInterval_ = other.deleteInterval_;
          onChanged();
        }
        if (other.hasOdsId()) {
          setOdsId(other.getOdsId());
        }
        if (other.hasInsertSql()) {
          bitField0_ |= 0x00000400;
          insertSql_ = other.insertSql_;
          onChanged();
        }
        if (other.hasDeleteSql()) {
          bitField0_ |= 0x00000800;
          deleteSql_ = other.deleteSql_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasTaskName()) {
          
          return false;
        }
        if (!hasTaskType()) {
          
          return false;
        }
        if (!hasNextInterval()) {
          
          return false;
        }
        if (!hasSourceDir()) {
          
          return false;
        }
        if (!hasStorageDir()) {
          
          return false;
        }
        if (!hasFileName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>required int32 appId = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskName_ = "";
      /**
       * <code>required string taskName = 3;</code>
       */
      public boolean hasTaskName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string taskName = 3;</code>
       */
      public java.lang.String getTaskName() {
        java.lang.Object ref = taskName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTaskNameBytes() {
        java.lang.Object ref = taskName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskName = 3;</code>
       */
      public Builder setTaskName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taskName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskName = 3;</code>
       */
      public Builder clearTaskName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taskName_ = getDefaultInstance().getTaskName();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskName = 3;</code>
       */
      public Builder setTaskNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        taskName_ = value;
        onChanged();
        return this;
      }

      private int taskType_ ;
      /**
       * <code>required int32 taskType = 4;</code>
       */
      public boolean hasTaskType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 taskType = 4;</code>
       */
      public int getTaskType() {
        return taskType_;
      }
      /**
       * <code>required int32 taskType = 4;</code>
       */
      public Builder setTaskType(int value) {
        bitField0_ |= 0x00000008;
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 taskType = 4;</code>
       */
      public Builder clearTaskType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskType_ = 0;
        onChanged();
        return this;
      }

      private int nextInterval_ ;
      /**
       * <code>required int32 nextInterval = 5;</code>
       */
      public boolean hasNextInterval() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 nextInterval = 5;</code>
       */
      public int getNextInterval() {
        return nextInterval_;
      }
      /**
       * <code>required int32 nextInterval = 5;</code>
       */
      public Builder setNextInterval(int value) {
        bitField0_ |= 0x00000010;
        nextInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nextInterval = 5;</code>
       */
      public Builder clearNextInterval() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nextInterval_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sourceDir_ = "";
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public boolean hasSourceDir() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public java.lang.String getSourceDir() {
        java.lang.Object ref = sourceDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSourceDirBytes() {
        java.lang.Object ref = sourceDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public Builder setSourceDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sourceDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public Builder clearSourceDir() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sourceDir_ = getDefaultInstance().getSourceDir();
        onChanged();
        return this;
      }
      /**
       * <code>required string sourceDir = 6;</code>
       */
      public Builder setSourceDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sourceDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object storageDir_ = "";
      /**
       * <code>required string storageDir = 7;</code>
       */
      public boolean hasStorageDir() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string storageDir = 7;</code>
       */
      public java.lang.String getStorageDir() {
        java.lang.Object ref = storageDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            storageDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string storageDir = 7;</code>
       */
      public com.google.protobuf.ByteString
          getStorageDirBytes() {
        java.lang.Object ref = storageDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storageDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string storageDir = 7;</code>
       */
      public Builder setStorageDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        storageDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string storageDir = 7;</code>
       */
      public Builder clearStorageDir() {
        bitField0_ = (bitField0_ & ~0x00000040);
        storageDir_ = getDefaultInstance().getStorageDir();
        onChanged();
        return this;
      }
      /**
       * <code>required string storageDir = 7;</code>
       */
      public Builder setStorageDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        storageDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>required string fileName = 8;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string fileName = 8;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileName = 8;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 8;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 8;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deleteInterval_ = "";
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public boolean hasDeleteInterval() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public java.lang.String getDeleteInterval() {
        java.lang.Object ref = deleteInterval_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deleteInterval_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDeleteIntervalBytes() {
        java.lang.Object ref = deleteInterval_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deleteInterval_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public Builder setDeleteInterval(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        deleteInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public Builder clearDeleteInterval() {
        bitField0_ = (bitField0_ & ~0x00000100);
        deleteInterval_ = getDefaultInstance().getDeleteInterval();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deleteInterval = 9;</code>
       */
      public Builder setDeleteIntervalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        deleteInterval_ = value;
        onChanged();
        return this;
      }

      private int odsId_ ;
      /**
       * <code>optional int32 odsId = 10;</code>
       */
      public boolean hasOdsId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 odsId = 10;</code>
       */
      public int getOdsId() {
        return odsId_;
      }
      /**
       * <code>optional int32 odsId = 10;</code>
       */
      public Builder setOdsId(int value) {
        bitField0_ |= 0x00000200;
        odsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 odsId = 10;</code>
       */
      public Builder clearOdsId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        odsId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object insertSql_ = "";
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public boolean hasInsertSql() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public java.lang.String getInsertSql() {
        java.lang.Object ref = insertSql_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            insertSql_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public com.google.protobuf.ByteString
          getInsertSqlBytes() {
        java.lang.Object ref = insertSql_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          insertSql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public Builder setInsertSql(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        insertSql_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public Builder clearInsertSql() {
        bitField0_ = (bitField0_ & ~0x00000400);
        insertSql_ = getDefaultInstance().getInsertSql();
        onChanged();
        return this;
      }
      /**
       * <code>optional string insertSql = 11;</code>
       */
      public Builder setInsertSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        insertSql_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deleteSql_ = "";
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public boolean hasDeleteSql() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public java.lang.String getDeleteSql() {
        java.lang.Object ref = deleteSql_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deleteSql_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public com.google.protobuf.ByteString
          getDeleteSqlBytes() {
        java.lang.Object ref = deleteSql_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deleteSql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public Builder setDeleteSql(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        deleteSql_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public Builder clearDeleteSql() {
        bitField0_ = (bitField0_ & ~0x00000800);
        deleteSql_ = getDefaultInstance().getDeleteSql();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deleteSql = 12;</code>
       */
      public Builder setDeleteSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        deleteSql_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FileTask)
    }

    static {
      defaultInstance = new FileTask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FileTask)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022db/file_task.proto\"\345\001\n\010FileTask\022\n\n\002id\030" +
      "\001 \002(\005\022\r\n\005appId\030\002 \002(\005\022\020\n\010taskName\030\003 \002(\t\022\020" +
      "\n\010taskType\030\004 \002(\005\022\024\n\014nextInterval\030\005 \002(\005\022\021" +
      "\n\tsourceDir\030\006 \002(\t\022\022\n\nstorageDir\030\007 \002(\t\022\020\n" +
      "\010fileName\030\010 \002(\t\022\026\n\016deleteInterval\030\t \001(\t\022" +
      "\r\n\005odsId\030\n \001(\005\022\021\n\tinsertSql\030\013 \001(\t\022\021\n\tdel" +
      "eteSql\030\014 \001(\tB<\n+cc.changic.platform.etl." +
      "base.model.db.protoB\rFileTaskProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FileTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FileTask_descriptor,
        new java.lang.String[] { "Id", "AppId", "TaskName", "TaskType", "NextInterval", "SourceDir", "StorageDir", "FileName", "DeleteInterval", "OdsId", "InsertSql", "DeleteSql", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
