// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/gamezone.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class GameZoneProto {
  private GameZoneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameZoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameZone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int32 appId = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 2;</code>
     */
    int getAppId();

    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    boolean hasGameZoneId();
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    int getGameZoneId();

    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    boolean hasGameZoneName();
    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    java.lang.String getGameZoneName();
    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    com.google.protobuf.ByteString
        getGameZoneNameBytes();

    /**
     * <code>required string etlClientIp = 5;</code>
     */
    boolean hasEtlClientIp();
    /**
     * <code>required string etlClientIp = 5;</code>
     */
    java.lang.String getEtlClientIp();
    /**
     * <code>required string etlClientIp = 5;</code>
     */
    com.google.protobuf.ByteString
        getEtlClientIpBytes();

    /**
     * <code>optional string dbIp = 6;</code>
     */
    boolean hasDbIp();
    /**
     * <code>optional string dbIp = 6;</code>
     */
    java.lang.String getDbIp();
    /**
     * <code>optional string dbIp = 6;</code>
     */
    com.google.protobuf.ByteString
        getDbIpBytes();

    /**
     * <code>optional int32 dbPort = 7;</code>
     */
    boolean hasDbPort();
    /**
     * <code>optional int32 dbPort = 7;</code>
     */
    int getDbPort();

    /**
     * <code>optional int32 timezone = 8 [default = 8];</code>
     */
    boolean hasTimezone();
    /**
     * <code>optional int32 timezone = 8 [default = 8];</code>
     */
    int getTimezone();

    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    boolean hasSite();
    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    java.lang.String getSite();
    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getSiteBytes();

    /**
     * <code>required int32 maxRunJob = 10;</code>
     */
    boolean hasMaxRunJob();
    /**
     * <code>required int32 maxRunJob = 10;</code>
     */
    int getMaxRunJob();

    /**
     * <code>required int32 gameZoneStatus = 11;</code>
     */
    boolean hasGameZoneStatus();
    /**
     * <code>required int32 gameZoneStatus = 11;</code>
     */
    int getGameZoneStatus();

    /**
     * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
     */
    boolean hasFileDeleteInterval();
    /**
     * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
     */
    int getFileDeleteInterval();
  }
  /**
   * Protobuf type {@code GameZone}
   */
  public static final class GameZone extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameZone)
      GameZoneOrBuilder {
    // Use GameZone.newBuilder() to construct.
    private GameZone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameZone(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameZone defaultInstance;
    public static GameZone getDefaultInstance() {
      return defaultInstance;
    }

    public GameZone getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameZone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              appId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gameZoneId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              gameZoneName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              etlClientIp_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              dbIp_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              dbPort_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              timezone_ = input.readInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              site_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              maxRunJob_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              gameZoneStatus_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              fileDeleteInterval_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.internal_static_GameZone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.internal_static_GameZone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.class, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder.class);
    }

    public static com.google.protobuf.Parser<GameZone> PARSER =
        new com.google.protobuf.AbstractParser<GameZone>() {
      public GameZone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameZone(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameZone> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>required int32 appId = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 appId = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int GAMEZONEID_FIELD_NUMBER = 3;
    private int gameZoneId_;
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    public boolean hasGameZoneId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    public int getGameZoneId() {
      return gameZoneId_;
    }

    public static final int GAMEZONENAME_FIELD_NUMBER = 4;
    private java.lang.Object gameZoneName_;
    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    public boolean hasGameZoneName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    public java.lang.String getGameZoneName() {
      java.lang.Object ref = gameZoneName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameZoneName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gameZoneName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGameZoneNameBytes() {
      java.lang.Object ref = gameZoneName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameZoneName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ETLCLIENTIP_FIELD_NUMBER = 5;
    private java.lang.Object etlClientIp_;
    /**
     * <code>required string etlClientIp = 5;</code>
     */
    public boolean hasEtlClientIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string etlClientIp = 5;</code>
     */
    public java.lang.String getEtlClientIp() {
      java.lang.Object ref = etlClientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          etlClientIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string etlClientIp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEtlClientIpBytes() {
      java.lang.Object ref = etlClientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        etlClientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DBIP_FIELD_NUMBER = 6;
    private java.lang.Object dbIp_;
    /**
     * <code>optional string dbIp = 6;</code>
     */
    public boolean hasDbIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string dbIp = 6;</code>
     */
    public java.lang.String getDbIp() {
      java.lang.Object ref = dbIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dbIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dbIp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDbIpBytes() {
      java.lang.Object ref = dbIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DBPORT_FIELD_NUMBER = 7;
    private int dbPort_;
    /**
     * <code>optional int32 dbPort = 7;</code>
     */
    public boolean hasDbPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 dbPort = 7;</code>
     */
    public int getDbPort() {
      return dbPort_;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 8;
    private int timezone_;
    /**
     * <code>optional int32 timezone = 8 [default = 8];</code>
     */
    public boolean hasTimezone() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 timezone = 8 [default = 8];</code>
     */
    public int getTimezone() {
      return timezone_;
    }

    public static final int SITE_FIELD_NUMBER = 9;
    private java.lang.Object site_;
    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    public boolean hasSite() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    public java.lang.String getSite() {
      java.lang.Object ref = site_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          site_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string site = 9 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getSiteBytes() {
      java.lang.Object ref = site_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        site_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAXRUNJOB_FIELD_NUMBER = 10;
    private int maxRunJob_;
    /**
     * <code>required int32 maxRunJob = 10;</code>
     */
    public boolean hasMaxRunJob() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 maxRunJob = 10;</code>
     */
    public int getMaxRunJob() {
      return maxRunJob_;
    }

    public static final int GAMEZONESTATUS_FIELD_NUMBER = 11;
    private int gameZoneStatus_;
    /**
     * <code>required int32 gameZoneStatus = 11;</code>
     */
    public boolean hasGameZoneStatus() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 gameZoneStatus = 11;</code>
     */
    public int getGameZoneStatus() {
      return gameZoneStatus_;
    }

    public static final int FILEDELETEINTERVAL_FIELD_NUMBER = 12;
    private int fileDeleteInterval_;
    /**
     * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
     */
    public boolean hasFileDeleteInterval() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
     */
    public int getFileDeleteInterval() {
      return fileDeleteInterval_;
    }

    private void initFields() {
      id_ = 0;
      appId_ = 0;
      gameZoneId_ = 0;
      gameZoneName_ = "";
      etlClientIp_ = "";
      dbIp_ = "";
      dbPort_ = 0;
      timezone_ = 8;
      site_ = "";
      maxRunJob_ = 0;
      gameZoneStatus_ = 0;
      fileDeleteInterval_ = 120;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameZoneId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEtlClientIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxRunJob()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameZoneStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gameZoneId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGameZoneNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEtlClientIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDbIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, dbPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, timezone_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getSiteBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, maxRunJob_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, gameZoneStatus_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, fileDeleteInterval_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gameZoneId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGameZoneNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEtlClientIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDbIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, dbPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, timezone_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getSiteBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, maxRunJob_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, gameZoneStatus_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, fileDeleteInterval_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameZone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameZone)
        cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.internal_static_GameZone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.internal_static_GameZone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.class, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gameZoneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gameZoneName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        etlClientIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        dbIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        dbPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        timezone_ = 8;
        bitField0_ = (bitField0_ & ~0x00000080);
        site_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        maxRunJob_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        gameZoneStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        fileDeleteInterval_ = 120;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.internal_static_GameZone_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone build() {
        cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone result = new cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gameZoneId_ = gameZoneId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gameZoneName_ = gameZoneName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.etlClientIp_ = etlClientIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dbIp_ = dbIp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dbPort_ = dbPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.timezone_ = timezone_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.site_ = site_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.maxRunJob_ = maxRunJob_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.gameZoneStatus_ = gameZoneStatus_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fileDeleteInterval_ = fileDeleteInterval_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasGameZoneId()) {
          setGameZoneId(other.getGameZoneId());
        }
        if (other.hasGameZoneName()) {
          bitField0_ |= 0x00000008;
          gameZoneName_ = other.gameZoneName_;
          onChanged();
        }
        if (other.hasEtlClientIp()) {
          bitField0_ |= 0x00000010;
          etlClientIp_ = other.etlClientIp_;
          onChanged();
        }
        if (other.hasDbIp()) {
          bitField0_ |= 0x00000020;
          dbIp_ = other.dbIp_;
          onChanged();
        }
        if (other.hasDbPort()) {
          setDbPort(other.getDbPort());
        }
        if (other.hasTimezone()) {
          setTimezone(other.getTimezone());
        }
        if (other.hasSite()) {
          bitField0_ |= 0x00000100;
          site_ = other.site_;
          onChanged();
        }
        if (other.hasMaxRunJob()) {
          setMaxRunJob(other.getMaxRunJob());
        }
        if (other.hasGameZoneStatus()) {
          setGameZoneStatus(other.getGameZoneStatus());
        }
        if (other.hasFileDeleteInterval()) {
          setFileDeleteInterval(other.getFileDeleteInterval());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasGameZoneId()) {
          
          return false;
        }
        if (!hasEtlClientIp()) {
          
          return false;
        }
        if (!hasMaxRunJob()) {
          
          return false;
        }
        if (!hasGameZoneStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>required int32 appId = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        onChanged();
        return this;
      }

      private int gameZoneId_ ;
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public boolean hasGameZoneId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public int getGameZoneId() {
        return gameZoneId_;
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public Builder setGameZoneId(int value) {
        bitField0_ |= 0x00000004;
        gameZoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public Builder clearGameZoneId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gameZoneId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object gameZoneName_ = "";
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public boolean hasGameZoneName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public java.lang.String getGameZoneName() {
        java.lang.Object ref = gameZoneName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gameZoneName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGameZoneNameBytes() {
        java.lang.Object ref = gameZoneName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameZoneName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public Builder setGameZoneName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gameZoneName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public Builder clearGameZoneName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gameZoneName_ = getDefaultInstance().getGameZoneName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameZoneName = 4;</code>
       */
      public Builder setGameZoneNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gameZoneName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object etlClientIp_ = "";
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public boolean hasEtlClientIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public java.lang.String getEtlClientIp() {
        java.lang.Object ref = etlClientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            etlClientIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEtlClientIpBytes() {
        java.lang.Object ref = etlClientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          etlClientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public Builder setEtlClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        etlClientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public Builder clearEtlClientIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        etlClientIp_ = getDefaultInstance().getEtlClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string etlClientIp = 5;</code>
       */
      public Builder setEtlClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        etlClientIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dbIp_ = "";
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public boolean hasDbIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public java.lang.String getDbIp() {
        java.lang.Object ref = dbIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dbIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDbIpBytes() {
        java.lang.Object ref = dbIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dbIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public Builder setDbIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dbIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public Builder clearDbIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dbIp_ = getDefaultInstance().getDbIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dbIp = 6;</code>
       */
      public Builder setDbIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dbIp_ = value;
        onChanged();
        return this;
      }

      private int dbPort_ ;
      /**
       * <code>optional int32 dbPort = 7;</code>
       */
      public boolean hasDbPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 dbPort = 7;</code>
       */
      public int getDbPort() {
        return dbPort_;
      }
      /**
       * <code>optional int32 dbPort = 7;</code>
       */
      public Builder setDbPort(int value) {
        bitField0_ |= 0x00000040;
        dbPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dbPort = 7;</code>
       */
      public Builder clearDbPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dbPort_ = 0;
        onChanged();
        return this;
      }

      private int timezone_ = 8;
      /**
       * <code>optional int32 timezone = 8 [default = 8];</code>
       */
      public boolean hasTimezone() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 timezone = 8 [default = 8];</code>
       */
      public int getTimezone() {
        return timezone_;
      }
      /**
       * <code>optional int32 timezone = 8 [default = 8];</code>
       */
      public Builder setTimezone(int value) {
        bitField0_ |= 0x00000080;
        timezone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timezone = 8 [default = 8];</code>
       */
      public Builder clearTimezone() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timezone_ = 8;
        onChanged();
        return this;
      }

      private java.lang.Object site_ = "";
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public boolean hasSite() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public java.lang.String getSite() {
        java.lang.Object ref = site_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            site_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getSiteBytes() {
        java.lang.Object ref = site_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          site_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public Builder setSite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        site_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public Builder clearSite() {
        bitField0_ = (bitField0_ & ~0x00000100);
        site_ = getDefaultInstance().getSite();
        onChanged();
        return this;
      }
      /**
       * <code>optional string site = 9 [default = ""];</code>
       */
      public Builder setSiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        site_ = value;
        onChanged();
        return this;
      }

      private int maxRunJob_ ;
      /**
       * <code>required int32 maxRunJob = 10;</code>
       */
      public boolean hasMaxRunJob() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 maxRunJob = 10;</code>
       */
      public int getMaxRunJob() {
        return maxRunJob_;
      }
      /**
       * <code>required int32 maxRunJob = 10;</code>
       */
      public Builder setMaxRunJob(int value) {
        bitField0_ |= 0x00000200;
        maxRunJob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 maxRunJob = 10;</code>
       */
      public Builder clearMaxRunJob() {
        bitField0_ = (bitField0_ & ~0x00000200);
        maxRunJob_ = 0;
        onChanged();
        return this;
      }

      private int gameZoneStatus_ ;
      /**
       * <code>required int32 gameZoneStatus = 11;</code>
       */
      public boolean hasGameZoneStatus() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 gameZoneStatus = 11;</code>
       */
      public int getGameZoneStatus() {
        return gameZoneStatus_;
      }
      /**
       * <code>required int32 gameZoneStatus = 11;</code>
       */
      public Builder setGameZoneStatus(int value) {
        bitField0_ |= 0x00000400;
        gameZoneStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gameZoneStatus = 11;</code>
       */
      public Builder clearGameZoneStatus() {
        bitField0_ = (bitField0_ & ~0x00000400);
        gameZoneStatus_ = 0;
        onChanged();
        return this;
      }

      private int fileDeleteInterval_ = 120;
      /**
       * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
       */
      public boolean hasFileDeleteInterval() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
       */
      public int getFileDeleteInterval() {
        return fileDeleteInterval_;
      }
      /**
       * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
       */
      public Builder setFileDeleteInterval(int value) {
        bitField0_ |= 0x00000800;
        fileDeleteInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fileDeleteInterval = 12 [default = 120];</code>
       */
      public Builder clearFileDeleteInterval() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fileDeleteInterval_ = 120;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameZone)
    }

    static {
      defaultInstance = new GameZone(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GameZone)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameZone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameZone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021db/gamezone.proto\"\363\001\n\010GameZone\022\n\n\002id\030\001" +
      " \002(\005\022\r\n\005appId\030\002 \002(\005\022\022\n\ngameZoneId\030\003 \002(\005\022" +
      "\024\n\014gameZoneName\030\004 \001(\t\022\023\n\013etlClientIp\030\005 \002" +
      "(\t\022\014\n\004dbIp\030\006 \001(\t\022\016\n\006dbPort\030\007 \001(\005\022\023\n\010time" +
      "zone\030\010 \001(\005:\0018\022\016\n\004site\030\t \001(\t:\000\022\021\n\tmaxRunJ" +
      "ob\030\n \002(\005\022\026\n\016gameZoneStatus\030\013 \002(\005\022\037\n\022file" +
      "DeleteInterval\030\014 \001(\005:\003120B<\n+cc.changic." +
      "platform.etl.base.model.db.protoB\rGameZo" +
      "neProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GameZone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameZone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameZone_descriptor,
        new java.lang.String[] { "Id", "AppId", "GameZoneId", "GameZoneName", "EtlClientIp", "DbIp", "DbPort", "Timezone", "Site", "MaxRunJob", "GameZoneStatus", "FileDeleteInterval", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
