// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/job.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class JobProto {
  private JobProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Job)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int32 appId = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 2;</code>
     */
    int getAppId();

    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    boolean hasGameZoneId();
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    int getGameZoneId();

    /**
     * <code>required string taskTable = 4;</code>
     */
    boolean hasTaskTable();
    /**
     * <code>required string taskTable = 4;</code>
     */
    java.lang.String getTaskTable();
    /**
     * <code>required string taskTable = 4;</code>
     */
    com.google.protobuf.ByteString
        getTaskTableBytes();

    /**
     * <code>required int32 taskId = 5;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required int32 taskId = 5;</code>
     */
    int getTaskId();

    /**
     * <code>optional int32 status = 6;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 6;</code>
     */
    int getStatus();

    /**
     * <code>optional string modifyTime = 7;</code>
     */
    boolean hasModifyTime();
    /**
     * <code>optional string modifyTime = 7;</code>
     */
    java.lang.String getModifyTime();
    /**
     * <code>optional string modifyTime = 7;</code>
     */
    com.google.protobuf.ByteString
        getModifyTimeBytes();

    /**
     * <code>optional string nextTime = 8;</code>
     */
    boolean hasNextTime();
    /**
     * <code>optional string nextTime = 8;</code>
     */
    java.lang.String getNextTime();
    /**
     * <code>optional string nextTime = 8;</code>
     */
    com.google.protobuf.ByteString
        getNextTimeBytes();

    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    boolean hasLastRecordTime();
    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    java.lang.String getLastRecordTime();
    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    com.google.protobuf.ByteString
        getLastRecordTimeBytes();

    /**
     * <code>optional int64 lastRecordId = 10;</code>
     */
    boolean hasLastRecordId();
    /**
     * <code>optional int64 lastRecordId = 10;</code>
     */
    long getLastRecordId();

    /**
     * <code>optional int64 lastRecordOffset = 11;</code>
     */
    boolean hasLastRecordOffset();
    /**
     * <code>optional int64 lastRecordOffset = 11;</code>
     */
    long getLastRecordOffset();

    /**
     * <code>optional string optionDesc = 12;</code>
     */
    boolean hasOptionDesc();
    /**
     * <code>optional string optionDesc = 12;</code>
     */
    java.lang.String getOptionDesc();
    /**
     * <code>optional string optionDesc = 12;</code>
     */
    com.google.protobuf.ByteString
        getOptionDescBytes();
  }
  /**
   * Protobuf type {@code Job}
   */
  public static final class Job extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Job)
      JobOrBuilder {
    // Use Job.newBuilder() to construct.
    private Job(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Job(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Job defaultInstance;
    public static Job getDefaultInstance() {
      return defaultInstance;
    }

    public Job getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Job(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              appId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gameZoneId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              taskTable_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              taskId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              status_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              modifyTime_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              nextTime_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              lastRecordTime_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              lastRecordId_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              lastRecordOffset_ = input.readInt64();
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              optionDesc_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.JobProto.internal_static_Job_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.JobProto.internal_static_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.JobProto.Job.class, cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder.class);
    }

    public static com.google.protobuf.Parser<Job> PARSER =
        new com.google.protobuf.AbstractParser<Job>() {
      public Job parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Job(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Job> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>required int32 appId = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 appId = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int GAMEZONEID_FIELD_NUMBER = 3;
    private int gameZoneId_;
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    public boolean hasGameZoneId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 gameZoneId = 3;</code>
     */
    public int getGameZoneId() {
      return gameZoneId_;
    }

    public static final int TASKTABLE_FIELD_NUMBER = 4;
    private java.lang.Object taskTable_;
    /**
     * <code>required string taskTable = 4;</code>
     */
    public boolean hasTaskTable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string taskTable = 4;</code>
     */
    public java.lang.String getTaskTable() {
      java.lang.Object ref = taskTable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskTable_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskTable = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTableBytes() {
      java.lang.Object ref = taskTable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskTable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 5;
    private int taskId_;
    /**
     * <code>required int32 taskId = 5;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 taskId = 5;</code>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>optional int32 status = 6;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 status = 6;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MODIFYTIME_FIELD_NUMBER = 7;
    private java.lang.Object modifyTime_;
    /**
     * <code>optional string modifyTime = 7;</code>
     */
    public boolean hasModifyTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string modifyTime = 7;</code>
     */
    public java.lang.String getModifyTime() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modifyTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string modifyTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getModifyTimeBytes() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEXTTIME_FIELD_NUMBER = 8;
    private java.lang.Object nextTime_;
    /**
     * <code>optional string nextTime = 8;</code>
     */
    public boolean hasNextTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string nextTime = 8;</code>
     */
    public java.lang.String getNextTime() {
      java.lang.Object ref = nextTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nextTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nextTime = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNextTimeBytes() {
      java.lang.Object ref = nextTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTRECORDTIME_FIELD_NUMBER = 9;
    private java.lang.Object lastRecordTime_;
    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    public boolean hasLastRecordTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    public java.lang.String getLastRecordTime() {
      java.lang.Object ref = lastRecordTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastRecordTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastRecordTime = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLastRecordTimeBytes() {
      java.lang.Object ref = lastRecordTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastRecordTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTRECORDID_FIELD_NUMBER = 10;
    private long lastRecordId_;
    /**
     * <code>optional int64 lastRecordId = 10;</code>
     */
    public boolean hasLastRecordId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 lastRecordId = 10;</code>
     */
    public long getLastRecordId() {
      return lastRecordId_;
    }

    public static final int LASTRECORDOFFSET_FIELD_NUMBER = 11;
    private long lastRecordOffset_;
    /**
     * <code>optional int64 lastRecordOffset = 11;</code>
     */
    public boolean hasLastRecordOffset() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 lastRecordOffset = 11;</code>
     */
    public long getLastRecordOffset() {
      return lastRecordOffset_;
    }

    public static final int OPTIONDESC_FIELD_NUMBER = 12;
    private java.lang.Object optionDesc_;
    /**
     * <code>optional string optionDesc = 12;</code>
     */
    public boolean hasOptionDesc() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string optionDesc = 12;</code>
     */
    public java.lang.String getOptionDesc() {
      java.lang.Object ref = optionDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          optionDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string optionDesc = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOptionDescBytes() {
      java.lang.Object ref = optionDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        optionDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      appId_ = 0;
      gameZoneId_ = 0;
      taskTable_ = "";
      taskId_ = 0;
      status_ = 0;
      modifyTime_ = "";
      nextTime_ = "";
      lastRecordTime_ = "";
      lastRecordId_ = 0L;
      lastRecordOffset_ = 0L;
      optionDesc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameZoneId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, gameZoneId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTaskTableBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, taskId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, status_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getModifyTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getNextTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLastRecordTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, lastRecordId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, lastRecordOffset_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getOptionDescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, gameZoneId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTaskTableBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, taskId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, status_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getModifyTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getNextTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLastRecordTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, lastRecordId_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, lastRecordOffset_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getOptionDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.JobProto.Job parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.JobProto.Job prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Job}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Job)
        cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.JobProto.internal_static_Job_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.JobProto.internal_static_Job_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.JobProto.Job.class, cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.JobProto.Job.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        gameZoneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        taskTable_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        modifyTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        nextTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        lastRecordTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        lastRecordId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        lastRecordOffset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        optionDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.JobProto.internal_static_Job_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.JobProto.Job getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.JobProto.Job build() {
        cc.changic.platform.etl.base.model.db.proto.JobProto.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.JobProto.Job buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.JobProto.Job result = new cc.changic.platform.etl.base.model.db.proto.JobProto.Job(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gameZoneId_ = gameZoneId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskTable_ = taskTable_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.modifyTime_ = modifyTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.nextTime_ = nextTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastRecordTime_ = lastRecordTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lastRecordId_ = lastRecordId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lastRecordOffset_ = lastRecordOffset_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.optionDesc_ = optionDesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.JobProto.Job) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.JobProto.Job)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.JobProto.Job other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasGameZoneId()) {
          setGameZoneId(other.getGameZoneId());
        }
        if (other.hasTaskTable()) {
          bitField0_ |= 0x00000008;
          taskTable_ = other.taskTable_;
          onChanged();
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasModifyTime()) {
          bitField0_ |= 0x00000040;
          modifyTime_ = other.modifyTime_;
          onChanged();
        }
        if (other.hasNextTime()) {
          bitField0_ |= 0x00000080;
          nextTime_ = other.nextTime_;
          onChanged();
        }
        if (other.hasLastRecordTime()) {
          bitField0_ |= 0x00000100;
          lastRecordTime_ = other.lastRecordTime_;
          onChanged();
        }
        if (other.hasLastRecordId()) {
          setLastRecordId(other.getLastRecordId());
        }
        if (other.hasLastRecordOffset()) {
          setLastRecordOffset(other.getLastRecordOffset());
        }
        if (other.hasOptionDesc()) {
          bitField0_ |= 0x00000800;
          optionDesc_ = other.optionDesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasGameZoneId()) {
          
          return false;
        }
        if (!hasTaskTable()) {
          
          return false;
        }
        if (!hasTaskId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.JobProto.Job parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.JobProto.Job) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>required int32 appId = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        onChanged();
        return this;
      }

      private int gameZoneId_ ;
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public boolean hasGameZoneId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public int getGameZoneId() {
        return gameZoneId_;
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public Builder setGameZoneId(int value) {
        bitField0_ |= 0x00000004;
        gameZoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gameZoneId = 3;</code>
       */
      public Builder clearGameZoneId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gameZoneId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskTable_ = "";
      /**
       * <code>required string taskTable = 4;</code>
       */
      public boolean hasTaskTable() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string taskTable = 4;</code>
       */
      public java.lang.String getTaskTable() {
        java.lang.Object ref = taskTable_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskTable_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskTable = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTableBytes() {
        java.lang.Object ref = taskTable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskTable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskTable = 4;</code>
       */
      public Builder setTaskTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskTable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskTable = 4;</code>
       */
      public Builder clearTaskTable() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskTable_ = getDefaultInstance().getTaskTable();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskTable = 4;</code>
       */
      public Builder setTaskTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskTable_ = value;
        onChanged();
        return this;
      }

      private int taskId_ ;
      /**
       * <code>required int32 taskId = 5;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 taskId = 5;</code>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>required int32 taskId = 5;</code>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000010;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 taskId = 5;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        taskId_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 6;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 status = 6;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 6;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 6;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modifyTime_ = "";
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public boolean hasModifyTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public java.lang.String getModifyTime() {
        java.lang.Object ref = modifyTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            modifyTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getModifyTimeBytes() {
        java.lang.Object ref = modifyTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modifyTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public Builder setModifyTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        modifyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public Builder clearModifyTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        modifyTime_ = getDefaultInstance().getModifyTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 7;</code>
       */
      public Builder setModifyTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        modifyTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nextTime_ = "";
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public boolean hasNextTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public java.lang.String getNextTime() {
        java.lang.Object ref = nextTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nextTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public com.google.protobuf.ByteString
          getNextTimeBytes() {
        java.lang.Object ref = nextTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nextTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public Builder setNextTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        nextTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public Builder clearNextTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nextTime_ = getDefaultInstance().getNextTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nextTime = 8;</code>
       */
      public Builder setNextTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        nextTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastRecordTime_ = "";
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public boolean hasLastRecordTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public java.lang.String getLastRecordTime() {
        java.lang.Object ref = lastRecordTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastRecordTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLastRecordTimeBytes() {
        java.lang.Object ref = lastRecordTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastRecordTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public Builder setLastRecordTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastRecordTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public Builder clearLastRecordTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastRecordTime_ = getDefaultInstance().getLastRecordTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastRecordTime = 9;</code>
       */
      public Builder setLastRecordTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastRecordTime_ = value;
        onChanged();
        return this;
      }

      private long lastRecordId_ ;
      /**
       * <code>optional int64 lastRecordId = 10;</code>
       */
      public boolean hasLastRecordId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 lastRecordId = 10;</code>
       */
      public long getLastRecordId() {
        return lastRecordId_;
      }
      /**
       * <code>optional int64 lastRecordId = 10;</code>
       */
      public Builder setLastRecordId(long value) {
        bitField0_ |= 0x00000200;
        lastRecordId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastRecordId = 10;</code>
       */
      public Builder clearLastRecordId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lastRecordId_ = 0L;
        onChanged();
        return this;
      }

      private long lastRecordOffset_ ;
      /**
       * <code>optional int64 lastRecordOffset = 11;</code>
       */
      public boolean hasLastRecordOffset() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 lastRecordOffset = 11;</code>
       */
      public long getLastRecordOffset() {
        return lastRecordOffset_;
      }
      /**
       * <code>optional int64 lastRecordOffset = 11;</code>
       */
      public Builder setLastRecordOffset(long value) {
        bitField0_ |= 0x00000400;
        lastRecordOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastRecordOffset = 11;</code>
       */
      public Builder clearLastRecordOffset() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lastRecordOffset_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object optionDesc_ = "";
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public boolean hasOptionDesc() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public java.lang.String getOptionDesc() {
        java.lang.Object ref = optionDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            optionDesc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public com.google.protobuf.ByteString
          getOptionDescBytes() {
        java.lang.Object ref = optionDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          optionDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public Builder setOptionDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        optionDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public Builder clearOptionDesc() {
        bitField0_ = (bitField0_ & ~0x00000800);
        optionDesc_ = getDefaultInstance().getOptionDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string optionDesc = 12;</code>
       */
      public Builder setOptionDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        optionDesc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Job)
    }

    static {
      defaultInstance = new Job(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Job)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Job_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Job_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014db/job.proto\"\351\001\n\003Job\022\n\n\002id\030\001 \002(\005\022\r\n\005ap" +
      "pId\030\002 \002(\005\022\022\n\ngameZoneId\030\003 \002(\005\022\021\n\ttaskTab" +
      "le\030\004 \002(\t\022\016\n\006taskId\030\005 \002(\005\022\016\n\006status\030\006 \001(\005" +
      "\022\022\n\nmodifyTime\030\007 \001(\t\022\020\n\010nextTime\030\010 \001(\t\022\026" +
      "\n\016lastRecordTime\030\t \001(\t\022\024\n\014lastRecordId\030\n" +
      " \001(\003\022\030\n\020lastRecordOffset\030\013 \001(\003\022\022\n\noption" +
      "Desc\030\014 \001(\tB7\n+cc.changic.platform.etl.ba" +
      "se.model.db.protoB\010JobProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Job_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Job_descriptor,
        new java.lang.String[] { "Id", "AppId", "GameZoneId", "TaskTable", "TaskId", "Status", "ModifyTime", "NextTime", "LastRecordTime", "LastRecordId", "LastRecordOffset", "OptionDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
