// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db/ods_config.proto

package cc.changic.platform.etl.base.model.db.proto;

public final class ODSConfigProto {
  private ODSConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ODSConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ODSConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string odsName = 2;</code>
     */
    boolean hasOdsName();
    /**
     * <code>required string odsName = 2;</code>
     */
    java.lang.String getOdsName();
    /**
     * <code>required string odsName = 2;</code>
     */
    com.google.protobuf.ByteString
        getOdsNameBytes();

    /**
     * <code>required string odsIp = 3;</code>
     */
    boolean hasOdsIp();
    /**
     * <code>required string odsIp = 3;</code>
     */
    java.lang.String getOdsIp();
    /**
     * <code>required string odsIp = 3;</code>
     */
    com.google.protobuf.ByteString
        getOdsIpBytes();

    /**
     * <code>required int32 odsPort = 4;</code>
     */
    boolean hasOdsPort();
    /**
     * <code>required int32 odsPort = 4;</code>
     */
    int getOdsPort();

    /**
     * <code>required string odsSchema = 5;</code>
     */
    boolean hasOdsSchema();
    /**
     * <code>required string odsSchema = 5;</code>
     */
    java.lang.String getOdsSchema();
    /**
     * <code>required string odsSchema = 5;</code>
     */
    com.google.protobuf.ByteString
        getOdsSchemaBytes();

    /**
     * <code>required string odsUser = 6;</code>
     */
    boolean hasOdsUser();
    /**
     * <code>required string odsUser = 6;</code>
     */
    java.lang.String getOdsUser();
    /**
     * <code>required string odsUser = 6;</code>
     */
    com.google.protobuf.ByteString
        getOdsUserBytes();

    /**
     * <code>required string odsPwd = 7;</code>
     */
    boolean hasOdsPwd();
    /**
     * <code>required string odsPwd = 7;</code>
     */
    java.lang.String getOdsPwd();
    /**
     * <code>required string odsPwd = 7;</code>
     */
    com.google.protobuf.ByteString
        getOdsPwdBytes();
  }
  /**
   * Protobuf type {@code ODSConfig}
   */
  public static final class ODSConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ODSConfig)
      ODSConfigOrBuilder {
    // Use ODSConfig.newBuilder() to construct.
    private ODSConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ODSConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ODSConfig defaultInstance;
    public static ODSConfig getDefaultInstance() {
      return defaultInstance;
    }

    public ODSConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ODSConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              odsName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              odsIp_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              odsPort_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              odsSchema_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              odsUser_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              odsPwd_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.internal_static_ODSConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.internal_static_ODSConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.class, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<ODSConfig> PARSER =
        new com.google.protobuf.AbstractParser<ODSConfig>() {
      public ODSConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ODSConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ODSConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ODSNAME_FIELD_NUMBER = 2;
    private java.lang.Object odsName_;
    /**
     * <code>required string odsName = 2;</code>
     */
    public boolean hasOdsName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string odsName = 2;</code>
     */
    public java.lang.String getOdsName() {
      java.lang.Object ref = odsName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          odsName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string odsName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOdsNameBytes() {
      java.lang.Object ref = odsName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odsName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ODSIP_FIELD_NUMBER = 3;
    private java.lang.Object odsIp_;
    /**
     * <code>required string odsIp = 3;</code>
     */
    public boolean hasOdsIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string odsIp = 3;</code>
     */
    public java.lang.String getOdsIp() {
      java.lang.Object ref = odsIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          odsIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string odsIp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOdsIpBytes() {
      java.lang.Object ref = odsIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odsIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ODSPORT_FIELD_NUMBER = 4;
    private int odsPort_;
    /**
     * <code>required int32 odsPort = 4;</code>
     */
    public boolean hasOdsPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 odsPort = 4;</code>
     */
    public int getOdsPort() {
      return odsPort_;
    }

    public static final int ODSSCHEMA_FIELD_NUMBER = 5;
    private java.lang.Object odsSchema_;
    /**
     * <code>required string odsSchema = 5;</code>
     */
    public boolean hasOdsSchema() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string odsSchema = 5;</code>
     */
    public java.lang.String getOdsSchema() {
      java.lang.Object ref = odsSchema_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          odsSchema_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string odsSchema = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOdsSchemaBytes() {
      java.lang.Object ref = odsSchema_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odsSchema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ODSUSER_FIELD_NUMBER = 6;
    private java.lang.Object odsUser_;
    /**
     * <code>required string odsUser = 6;</code>
     */
    public boolean hasOdsUser() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string odsUser = 6;</code>
     */
    public java.lang.String getOdsUser() {
      java.lang.Object ref = odsUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          odsUser_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string odsUser = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOdsUserBytes() {
      java.lang.Object ref = odsUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odsUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ODSPWD_FIELD_NUMBER = 7;
    private java.lang.Object odsPwd_;
    /**
     * <code>required string odsPwd = 7;</code>
     */
    public boolean hasOdsPwd() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string odsPwd = 7;</code>
     */
    public java.lang.String getOdsPwd() {
      java.lang.Object ref = odsPwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          odsPwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string odsPwd = 7;</code>
     */
    public com.google.protobuf.ByteString
        getOdsPwdBytes() {
      java.lang.Object ref = odsPwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        odsPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      odsName_ = "";
      odsIp_ = "";
      odsPort_ = 0;
      odsSchema_ = "";
      odsUser_ = "";
      odsPwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsSchema()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOdsPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOdsNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOdsIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, odsPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getOdsSchemaBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getOdsUserBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getOdsPwdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOdsNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOdsIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, odsPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getOdsSchemaBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getOdsUserBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getOdsPwdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ODSConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ODSConfig)
        cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.internal_static_ODSConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.internal_static_ODSConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.class, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder.class);
      }

      // Construct using cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        odsName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        odsIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        odsPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        odsSchema_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        odsUser_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        odsPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.internal_static_ODSConfig_descriptor;
      }

      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig getDefaultInstanceForType() {
        return cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance();
      }

      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig build() {
        cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig buildPartial() {
        cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig result = new cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.odsName_ = odsName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.odsIp_ = odsIp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.odsPort_ = odsPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.odsSchema_ = odsSchema_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.odsUser_ = odsUser_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.odsPwd_ = odsPwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig) {
          return mergeFrom((cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig other) {
        if (other == cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOdsName()) {
          bitField0_ |= 0x00000002;
          odsName_ = other.odsName_;
          onChanged();
        }
        if (other.hasOdsIp()) {
          bitField0_ |= 0x00000004;
          odsIp_ = other.odsIp_;
          onChanged();
        }
        if (other.hasOdsPort()) {
          setOdsPort(other.getOdsPort());
        }
        if (other.hasOdsSchema()) {
          bitField0_ |= 0x00000010;
          odsSchema_ = other.odsSchema_;
          onChanged();
        }
        if (other.hasOdsUser()) {
          bitField0_ |= 0x00000020;
          odsUser_ = other.odsUser_;
          onChanged();
        }
        if (other.hasOdsPwd()) {
          bitField0_ |= 0x00000040;
          odsPwd_ = other.odsPwd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasOdsName()) {
          
          return false;
        }
        if (!hasOdsIp()) {
          
          return false;
        }
        if (!hasOdsPort()) {
          
          return false;
        }
        if (!hasOdsSchema()) {
          
          return false;
        }
        if (!hasOdsUser()) {
          
          return false;
        }
        if (!hasOdsPwd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object odsName_ = "";
      /**
       * <code>required string odsName = 2;</code>
       */
      public boolean hasOdsName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string odsName = 2;</code>
       */
      public java.lang.String getOdsName() {
        java.lang.Object ref = odsName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            odsName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string odsName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOdsNameBytes() {
        java.lang.Object ref = odsName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odsName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string odsName = 2;</code>
       */
      public Builder setOdsName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        odsName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string odsName = 2;</code>
       */
      public Builder clearOdsName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        odsName_ = getDefaultInstance().getOdsName();
        onChanged();
        return this;
      }
      /**
       * <code>required string odsName = 2;</code>
       */
      public Builder setOdsNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        odsName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object odsIp_ = "";
      /**
       * <code>required string odsIp = 3;</code>
       */
      public boolean hasOdsIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string odsIp = 3;</code>
       */
      public java.lang.String getOdsIp() {
        java.lang.Object ref = odsIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            odsIp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string odsIp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOdsIpBytes() {
        java.lang.Object ref = odsIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odsIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string odsIp = 3;</code>
       */
      public Builder setOdsIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        odsIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string odsIp = 3;</code>
       */
      public Builder clearOdsIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        odsIp_ = getDefaultInstance().getOdsIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string odsIp = 3;</code>
       */
      public Builder setOdsIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        odsIp_ = value;
        onChanged();
        return this;
      }

      private int odsPort_ ;
      /**
       * <code>required int32 odsPort = 4;</code>
       */
      public boolean hasOdsPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 odsPort = 4;</code>
       */
      public int getOdsPort() {
        return odsPort_;
      }
      /**
       * <code>required int32 odsPort = 4;</code>
       */
      public Builder setOdsPort(int value) {
        bitField0_ |= 0x00000008;
        odsPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 odsPort = 4;</code>
       */
      public Builder clearOdsPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        odsPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object odsSchema_ = "";
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public boolean hasOdsSchema() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public java.lang.String getOdsSchema() {
        java.lang.Object ref = odsSchema_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            odsSchema_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOdsSchemaBytes() {
        java.lang.Object ref = odsSchema_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odsSchema_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public Builder setOdsSchema(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        odsSchema_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public Builder clearOdsSchema() {
        bitField0_ = (bitField0_ & ~0x00000010);
        odsSchema_ = getDefaultInstance().getOdsSchema();
        onChanged();
        return this;
      }
      /**
       * <code>required string odsSchema = 5;</code>
       */
      public Builder setOdsSchemaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        odsSchema_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object odsUser_ = "";
      /**
       * <code>required string odsUser = 6;</code>
       */
      public boolean hasOdsUser() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string odsUser = 6;</code>
       */
      public java.lang.String getOdsUser() {
        java.lang.Object ref = odsUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            odsUser_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string odsUser = 6;</code>
       */
      public com.google.protobuf.ByteString
          getOdsUserBytes() {
        java.lang.Object ref = odsUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odsUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string odsUser = 6;</code>
       */
      public Builder setOdsUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        odsUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string odsUser = 6;</code>
       */
      public Builder clearOdsUser() {
        bitField0_ = (bitField0_ & ~0x00000020);
        odsUser_ = getDefaultInstance().getOdsUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string odsUser = 6;</code>
       */
      public Builder setOdsUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        odsUser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object odsPwd_ = "";
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public boolean hasOdsPwd() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public java.lang.String getOdsPwd() {
        java.lang.Object ref = odsPwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            odsPwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public com.google.protobuf.ByteString
          getOdsPwdBytes() {
        java.lang.Object ref = odsPwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          odsPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public Builder setOdsPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        odsPwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public Builder clearOdsPwd() {
        bitField0_ = (bitField0_ & ~0x00000040);
        odsPwd_ = getDefaultInstance().getOdsPwd();
        onChanged();
        return this;
      }
      /**
       * <code>required string odsPwd = 7;</code>
       */
      public Builder setOdsPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        odsPwd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ODSConfig)
    }

    static {
      defaultInstance = new ODSConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ODSConfig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ODSConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ODSConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023db/ods_config.proto\"|\n\tODSConfig\022\n\n\002id" +
      "\030\001 \002(\005\022\017\n\007odsName\030\002 \002(\t\022\r\n\005odsIp\030\003 \002(\t\022\017" +
      "\n\007odsPort\030\004 \002(\005\022\021\n\todsSchema\030\005 \002(\t\022\017\n\007od" +
      "sUser\030\006 \002(\t\022\016\n\006odsPwd\030\007 \002(\tB=\n+cc.changi" +
      "c.platform.etl.base.model.db.protoB\016ODSC" +
      "onfigProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ODSConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ODSConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ODSConfig_descriptor,
        new java.lang.String[] { "Id", "OdsName", "OdsIp", "OdsPort", "OdsSchema", "OdsUser", "OdsPwd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
