// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_job.proto

package cc.changic.platform.etl.protocol;

public final class FileJobProto {
  private FileJobProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileJobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileJob)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string fileName = 1;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string fileName = 1;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string fileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional string sourceDir = 2;</code>
     */
    boolean hasSourceDir();
    /**
     * <code>optional string sourceDir = 2;</code>
     */
    java.lang.String getSourceDir();
    /**
     * <code>optional string sourceDir = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceDirBytes();

    /**
     * <code>optional string storageDir = 3;</code>
     */
    boolean hasStorageDir();
    /**
     * <code>optional string storageDir = 3;</code>
     */
    java.lang.String getStorageDir();
    /**
     * <code>optional string storageDir = 3;</code>
     */
    com.google.protobuf.ByteString
        getStorageDirBytes();

    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    boolean hasMd5();
    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    java.lang.String getMd5();
    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    /**
     * <code>optional int64 incrementalOffset = 5;</code>
     *
     * <pre>
     * 增量拉取时每次增量的字节数
     * </pre>
     */
    boolean hasIncrementalOffset();
    /**
     * <code>optional int64 incrementalOffset = 5;</code>
     *
     * <pre>
     * 增量拉取时每次增量的字节数
     * </pre>
     */
    long getIncrementalOffset();

    /**
     * <code>required .App app = 6;</code>
     */
    boolean hasApp();
    /**
     * <code>required .App app = 6;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.AppProto.App getApp();
    /**
     * <code>required .App app = 6;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder getAppOrBuilder();

    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    boolean hasGameZone();
    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone getGameZone();
    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder getGameZoneOrBuilder();

    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    boolean hasOdsConfig();
    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig getOdsConfig();
    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder getOdsConfigOrBuilder();

    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    boolean hasFileTask();
    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask getFileTask();
    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder getFileTaskOrBuilder();

    /**
     * <code>required .Job job = 10;</code>
     */
    boolean hasJob();
    /**
     * <code>required .Job job = 10;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.JobProto.Job getJob();
    /**
     * <code>required .Job job = 10;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder getJobOrBuilder();

    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    boolean hasVersion();
    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion getVersion();
    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder getVersionOrBuilder();
  }
  /**
   * Protobuf type {@code FileJob}
   */
  public static final class FileJob extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FileJob)
      FileJobOrBuilder {
    // Use FileJob.newBuilder() to construct.
    private FileJob(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileJob(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileJob defaultInstance;
    public static FileJob getDefaultInstance() {
      return defaultInstance;
    }

    public FileJob getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileJob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fileName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sourceDir_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              storageDir_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              md5_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              incrementalOffset_ = input.readInt64();
              break;
            }
            case 50: {
              cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = app_.toBuilder();
              }
              app_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.AppProto.App.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(app_);
                app_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = gameZone_.toBuilder();
              }
              gameZone_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gameZone_);
                gameZone_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = odsConfig_.toBuilder();
              }
              odsConfig_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(odsConfig_);
                odsConfig_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = fileTask_.toBuilder();
              }
              fileTask_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fileTask_);
                fileTask_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = job_.toBuilder();
              }
              job_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.JobProto.Job.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(job_);
                job_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 90: {
              cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = version_.toBuilder();
              }
              version_ = input.readMessage(cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(version_);
                version_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.changic.platform.etl.protocol.FileJobProto.internal_static_FileJob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.changic.platform.etl.protocol.FileJobProto.internal_static_FileJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.changic.platform.etl.protocol.FileJobProto.FileJob.class, cc.changic.platform.etl.protocol.FileJobProto.FileJob.Builder.class);
    }

    public static com.google.protobuf.Parser<FileJob> PARSER =
        new com.google.protobuf.AbstractParser<FileJob>() {
      public FileJob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileJob(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileJob> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object fileName_;
    /**
     * <code>optional string fileName = 1;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string fileName = 1;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEDIR_FIELD_NUMBER = 2;
    private java.lang.Object sourceDir_;
    /**
     * <code>optional string sourceDir = 2;</code>
     */
    public boolean hasSourceDir() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sourceDir = 2;</code>
     */
    public java.lang.String getSourceDir() {
      java.lang.Object ref = sourceDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sourceDir = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceDirBytes() {
      java.lang.Object ref = sourceDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORAGEDIR_FIELD_NUMBER = 3;
    private java.lang.Object storageDir_;
    /**
     * <code>optional string storageDir = 3;</code>
     */
    public boolean hasStorageDir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string storageDir = 3;</code>
     */
    public java.lang.String getStorageDir() {
      java.lang.Object ref = storageDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          storageDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string storageDir = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStorageDirBytes() {
      java.lang.Object ref = storageDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MD5_FIELD_NUMBER = 4;
    private java.lang.Object md5_;
    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    public boolean hasMd5() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          md5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string md5 = 4;</code>
     *
     * <pre>
     * 全量拉取时文件的MD5值
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INCREMENTALOFFSET_FIELD_NUMBER = 5;
    private long incrementalOffset_;
    /**
     * <code>optional int64 incrementalOffset = 5;</code>
     *
     * <pre>
     * 增量拉取时每次增量的字节数
     * </pre>
     */
    public boolean hasIncrementalOffset() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 incrementalOffset = 5;</code>
     *
     * <pre>
     * 增量拉取时每次增量的字节数
     * </pre>
     */
    public long getIncrementalOffset() {
      return incrementalOffset_;
    }

    public static final int APP_FIELD_NUMBER = 6;
    private cc.changic.platform.etl.base.model.db.proto.AppProto.App app_;
    /**
     * <code>required .App app = 6;</code>
     */
    public boolean hasApp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .App app = 6;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.AppProto.App getApp() {
      return app_;
    }
    /**
     * <code>required .App app = 6;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder getAppOrBuilder() {
      return app_;
    }

    public static final int GAMEZONE_FIELD_NUMBER = 7;
    private cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone gameZone_;
    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    public boolean hasGameZone() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone getGameZone() {
      return gameZone_;
    }
    /**
     * <code>required .GameZone gameZone = 7;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder getGameZoneOrBuilder() {
      return gameZone_;
    }

    public static final int ODSCONFIG_FIELD_NUMBER = 8;
    private cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig odsConfig_;
    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    public boolean hasOdsConfig() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig getOdsConfig() {
      return odsConfig_;
    }
    /**
     * <code>optional .ODSConfig odsConfig = 8;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder getOdsConfigOrBuilder() {
      return odsConfig_;
    }

    public static final int FILETASK_FIELD_NUMBER = 9;
    private cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask fileTask_;
    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    public boolean hasFileTask() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask getFileTask() {
      return fileTask_;
    }
    /**
     * <code>required .FileTask fileTask = 9;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder getFileTaskOrBuilder() {
      return fileTask_;
    }

    public static final int JOB_FIELD_NUMBER = 10;
    private cc.changic.platform.etl.base.model.db.proto.JobProto.Job job_;
    /**
     * <code>required .Job job = 10;</code>
     */
    public boolean hasJob() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required .Job job = 10;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.JobProto.Job getJob() {
      return job_;
    }
    /**
     * <code>required .Job job = 10;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder getJobOrBuilder() {
      return job_;
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion version_;
    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion getVersion() {
      return version_;
    }
    /**
     * <code>required .ConfigVersion version = 11;</code>
     */
    public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder getVersionOrBuilder() {
      return version_;
    }

    private void initFields() {
      fileName_ = "";
      sourceDir_ = "";
      storageDir_ = "";
      md5_ = "";
      incrementalOffset_ = 0L;
      app_ = cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance();
      gameZone_ = cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance();
      odsConfig_ = cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance();
      fileTask_ = cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance();
      job_ = cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance();
      version_ = cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasApp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameZone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJob()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getApp().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGameZone().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasOdsConfig()) {
        if (!getOdsConfig().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getFileTask().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getJob().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getVersion().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSourceDirBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStorageDirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, incrementalOffset_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, app_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, gameZone_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, odsConfig_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, fileTask_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, job_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(11, version_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSourceDirBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStorageDirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMd5Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, incrementalOffset_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, app_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, gameZone_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, odsConfig_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, fileTask_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, job_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.changic.platform.etl.protocol.FileJobProto.FileJob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.changic.platform.etl.protocol.FileJobProto.FileJob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileJob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileJob)
        cc.changic.platform.etl.protocol.FileJobProto.FileJobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.changic.platform.etl.protocol.FileJobProto.internal_static_FileJob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.changic.platform.etl.protocol.FileJobProto.internal_static_FileJob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.changic.platform.etl.protocol.FileJobProto.FileJob.class, cc.changic.platform.etl.protocol.FileJobProto.FileJob.Builder.class);
      }

      // Construct using cc.changic.platform.etl.protocol.FileJobProto.FileJob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppFieldBuilder();
          getGameZoneFieldBuilder();
          getOdsConfigFieldBuilder();
          getFileTaskFieldBuilder();
          getJobFieldBuilder();
          getVersionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        storageDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        md5_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        incrementalOffset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (appBuilder_ == null) {
          app_ = cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance();
        } else {
          appBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (gameZoneBuilder_ == null) {
          gameZone_ = cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance();
        } else {
          gameZoneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (odsConfigBuilder_ == null) {
          odsConfig_ = cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance();
        } else {
          odsConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (fileTaskBuilder_ == null) {
          fileTask_ = cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance();
        } else {
          fileTaskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (jobBuilder_ == null) {
          job_ = cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance();
        } else {
          jobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        if (versionBuilder_ == null) {
          version_ = cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance();
        } else {
          versionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.changic.platform.etl.protocol.FileJobProto.internal_static_FileJob_descriptor;
      }

      public cc.changic.platform.etl.protocol.FileJobProto.FileJob getDefaultInstanceForType() {
        return cc.changic.platform.etl.protocol.FileJobProto.FileJob.getDefaultInstance();
      }

      public cc.changic.platform.etl.protocol.FileJobProto.FileJob build() {
        cc.changic.platform.etl.protocol.FileJobProto.FileJob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.changic.platform.etl.protocol.FileJobProto.FileJob buildPartial() {
        cc.changic.platform.etl.protocol.FileJobProto.FileJob result = new cc.changic.platform.etl.protocol.FileJobProto.FileJob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceDir_ = sourceDir_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.storageDir_ = storageDir_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.md5_ = md5_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.incrementalOffset_ = incrementalOffset_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (appBuilder_ == null) {
          result.app_ = app_;
        } else {
          result.app_ = appBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (gameZoneBuilder_ == null) {
          result.gameZone_ = gameZone_;
        } else {
          result.gameZone_ = gameZoneBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (odsConfigBuilder_ == null) {
          result.odsConfig_ = odsConfig_;
        } else {
          result.odsConfig_ = odsConfigBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (fileTaskBuilder_ == null) {
          result.fileTask_ = fileTask_;
        } else {
          result.fileTask_ = fileTaskBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (jobBuilder_ == null) {
          result.job_ = job_;
        } else {
          result.job_ = jobBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (versionBuilder_ == null) {
          result.version_ = version_;
        } else {
          result.version_ = versionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.changic.platform.etl.protocol.FileJobProto.FileJob) {
          return mergeFrom((cc.changic.platform.etl.protocol.FileJobProto.FileJob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.changic.platform.etl.protocol.FileJobProto.FileJob other) {
        if (other == cc.changic.platform.etl.protocol.FileJobProto.FileJob.getDefaultInstance()) return this;
        if (other.hasFileName()) {
          bitField0_ |= 0x00000001;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasSourceDir()) {
          bitField0_ |= 0x00000002;
          sourceDir_ = other.sourceDir_;
          onChanged();
        }
        if (other.hasStorageDir()) {
          bitField0_ |= 0x00000004;
          storageDir_ = other.storageDir_;
          onChanged();
        }
        if (other.hasMd5()) {
          bitField0_ |= 0x00000008;
          md5_ = other.md5_;
          onChanged();
        }
        if (other.hasIncrementalOffset()) {
          setIncrementalOffset(other.getIncrementalOffset());
        }
        if (other.hasApp()) {
          mergeApp(other.getApp());
        }
        if (other.hasGameZone()) {
          mergeGameZone(other.getGameZone());
        }
        if (other.hasOdsConfig()) {
          mergeOdsConfig(other.getOdsConfig());
        }
        if (other.hasFileTask()) {
          mergeFileTask(other.getFileTask());
        }
        if (other.hasJob()) {
          mergeJob(other.getJob());
        }
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasApp()) {
          
          return false;
        }
        if (!hasGameZone()) {
          
          return false;
        }
        if (!hasFileTask()) {
          
          return false;
        }
        if (!hasJob()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!getApp().isInitialized()) {
          
          return false;
        }
        if (!getGameZone().isInitialized()) {
          
          return false;
        }
        if (hasOdsConfig()) {
          if (!getOdsConfig().isInitialized()) {
            
            return false;
          }
        }
        if (!getFileTask().isInitialized()) {
          
          return false;
        }
        if (!getJob().isInitialized()) {
          
          return false;
        }
        if (!getVersion().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.changic.platform.etl.protocol.FileJobProto.FileJob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.changic.platform.etl.protocol.FileJobProto.FileJob) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string fileName = 1;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string fileName = 1;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fileName = 1;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 1;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fileName = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceDir_ = "";
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public boolean hasSourceDir() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public java.lang.String getSourceDir() {
        java.lang.Object ref = sourceDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceDirBytes() {
        java.lang.Object ref = sourceDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public Builder setSourceDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public Builder clearSourceDir() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceDir_ = getDefaultInstance().getSourceDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sourceDir = 2;</code>
       */
      public Builder setSourceDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object storageDir_ = "";
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public boolean hasStorageDir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public java.lang.String getStorageDir() {
        java.lang.Object ref = storageDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            storageDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStorageDirBytes() {
        java.lang.Object ref = storageDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          storageDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public Builder setStorageDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        storageDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public Builder clearStorageDir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        storageDir_ = getDefaultInstance().getStorageDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string storageDir = 3;</code>
       */
      public Builder setStorageDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        storageDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object md5_ = "";
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public boolean hasMd5() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            md5_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public Builder clearMd5() {
        bitField0_ = (bitField0_ & ~0x00000008);
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string md5 = 4;</code>
       *
       * <pre>
       * 全量拉取时文件的MD5值
       * </pre>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        md5_ = value;
        onChanged();
        return this;
      }

      private long incrementalOffset_ ;
      /**
       * <code>optional int64 incrementalOffset = 5;</code>
       *
       * <pre>
       * 增量拉取时每次增量的字节数
       * </pre>
       */
      public boolean hasIncrementalOffset() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 incrementalOffset = 5;</code>
       *
       * <pre>
       * 增量拉取时每次增量的字节数
       * </pre>
       */
      public long getIncrementalOffset() {
        return incrementalOffset_;
      }
      /**
       * <code>optional int64 incrementalOffset = 5;</code>
       *
       * <pre>
       * 增量拉取时每次增量的字节数
       * </pre>
       */
      public Builder setIncrementalOffset(long value) {
        bitField0_ |= 0x00000010;
        incrementalOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 incrementalOffset = 5;</code>
       *
       * <pre>
       * 增量拉取时每次增量的字节数
       * </pre>
       */
      public Builder clearIncrementalOffset() {
        bitField0_ = (bitField0_ & ~0x00000010);
        incrementalOffset_ = 0L;
        onChanged();
        return this;
      }

      private cc.changic.platform.etl.base.model.db.proto.AppProto.App app_ = cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.AppProto.App, cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder, cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder> appBuilder_;
      /**
       * <code>required .App app = 6;</code>
       */
      public boolean hasApp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.AppProto.App getApp() {
        if (appBuilder_ == null) {
          return app_;
        } else {
          return appBuilder_.getMessage();
        }
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public Builder setApp(cc.changic.platform.etl.base.model.db.proto.AppProto.App value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          app_ = value;
          onChanged();
        } else {
          appBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public Builder setApp(
          cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder builderForValue) {
        if (appBuilder_ == null) {
          app_ = builderForValue.build();
          onChanged();
        } else {
          appBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public Builder mergeApp(cc.changic.platform.etl.base.model.db.proto.AppProto.App value) {
        if (appBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              app_ != cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance()) {
            app_ =
              cc.changic.platform.etl.base.model.db.proto.AppProto.App.newBuilder(app_).mergeFrom(value).buildPartial();
          } else {
            app_ = value;
          }
          onChanged();
        } else {
          appBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public Builder clearApp() {
        if (appBuilder_ == null) {
          app_ = cc.changic.platform.etl.base.model.db.proto.AppProto.App.getDefaultInstance();
          onChanged();
        } else {
          appBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder getAppBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getAppFieldBuilder().getBuilder();
      }
      /**
       * <code>required .App app = 6;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder getAppOrBuilder() {
        if (appBuilder_ != null) {
          return appBuilder_.getMessageOrBuilder();
        } else {
          return app_;
        }
      }
      /**
       * <code>required .App app = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.AppProto.App, cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder, cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder> 
          getAppFieldBuilder() {
        if (appBuilder_ == null) {
          appBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.AppProto.App, cc.changic.platform.etl.base.model.db.proto.AppProto.App.Builder, cc.changic.platform.etl.base.model.db.proto.AppProto.AppOrBuilder>(
                  getApp(),
                  getParentForChildren(),
                  isClean());
          app_ = null;
        }
        return appBuilder_;
      }

      private cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone gameZone_ = cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder> gameZoneBuilder_;
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public boolean hasGameZone() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone getGameZone() {
        if (gameZoneBuilder_ == null) {
          return gameZone_;
        } else {
          return gameZoneBuilder_.getMessage();
        }
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public Builder setGameZone(cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone value) {
        if (gameZoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameZone_ = value;
          onChanged();
        } else {
          gameZoneBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public Builder setGameZone(
          cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder builderForValue) {
        if (gameZoneBuilder_ == null) {
          gameZone_ = builderForValue.build();
          onChanged();
        } else {
          gameZoneBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public Builder mergeGameZone(cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone value) {
        if (gameZoneBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              gameZone_ != cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance()) {
            gameZone_ =
              cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.newBuilder(gameZone_).mergeFrom(value).buildPartial();
          } else {
            gameZone_ = value;
          }
          onChanged();
        } else {
          gameZoneBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public Builder clearGameZone() {
        if (gameZoneBuilder_ == null) {
          gameZone_ = cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.getDefaultInstance();
          onChanged();
        } else {
          gameZoneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder getGameZoneBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getGameZoneFieldBuilder().getBuilder();
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder getGameZoneOrBuilder() {
        if (gameZoneBuilder_ != null) {
          return gameZoneBuilder_.getMessageOrBuilder();
        } else {
          return gameZone_;
        }
      }
      /**
       * <code>required .GameZone gameZone = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder> 
          getGameZoneFieldBuilder() {
        if (gameZoneBuilder_ == null) {
          gameZoneBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZone.Builder, cc.changic.platform.etl.base.model.db.proto.GameZoneProto.GameZoneOrBuilder>(
                  getGameZone(),
                  getParentForChildren(),
                  isClean());
          gameZone_ = null;
        }
        return gameZoneBuilder_;
      }

      private cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig odsConfig_ = cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder> odsConfigBuilder_;
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public boolean hasOdsConfig() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig getOdsConfig() {
        if (odsConfigBuilder_ == null) {
          return odsConfig_;
        } else {
          return odsConfigBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public Builder setOdsConfig(cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig value) {
        if (odsConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          odsConfig_ = value;
          onChanged();
        } else {
          odsConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public Builder setOdsConfig(
          cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder builderForValue) {
        if (odsConfigBuilder_ == null) {
          odsConfig_ = builderForValue.build();
          onChanged();
        } else {
          odsConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public Builder mergeOdsConfig(cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig value) {
        if (odsConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              odsConfig_ != cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance()) {
            odsConfig_ =
              cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.newBuilder(odsConfig_).mergeFrom(value).buildPartial();
          } else {
            odsConfig_ = value;
          }
          onChanged();
        } else {
          odsConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public Builder clearOdsConfig() {
        if (odsConfigBuilder_ == null) {
          odsConfig_ = cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.getDefaultInstance();
          onChanged();
        } else {
          odsConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder getOdsConfigBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getOdsConfigFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder getOdsConfigOrBuilder() {
        if (odsConfigBuilder_ != null) {
          return odsConfigBuilder_.getMessageOrBuilder();
        } else {
          return odsConfig_;
        }
      }
      /**
       * <code>optional .ODSConfig odsConfig = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder> 
          getOdsConfigFieldBuilder() {
        if (odsConfigBuilder_ == null) {
          odsConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfig.Builder, cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.ODSConfigOrBuilder>(
                  getOdsConfig(),
                  getParentForChildren(),
                  isClean());
          odsConfig_ = null;
        }
        return odsConfigBuilder_;
      }

      private cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask fileTask_ = cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder> fileTaskBuilder_;
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public boolean hasFileTask() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask getFileTask() {
        if (fileTaskBuilder_ == null) {
          return fileTask_;
        } else {
          return fileTaskBuilder_.getMessage();
        }
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public Builder setFileTask(cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask value) {
        if (fileTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileTask_ = value;
          onChanged();
        } else {
          fileTaskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public Builder setFileTask(
          cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder builderForValue) {
        if (fileTaskBuilder_ == null) {
          fileTask_ = builderForValue.build();
          onChanged();
        } else {
          fileTaskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public Builder mergeFileTask(cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask value) {
        if (fileTaskBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              fileTask_ != cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance()) {
            fileTask_ =
              cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.newBuilder(fileTask_).mergeFrom(value).buildPartial();
          } else {
            fileTask_ = value;
          }
          onChanged();
        } else {
          fileTaskBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public Builder clearFileTask() {
        if (fileTaskBuilder_ == null) {
          fileTask_ = cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.getDefaultInstance();
          onChanged();
        } else {
          fileTaskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder getFileTaskBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getFileTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder getFileTaskOrBuilder() {
        if (fileTaskBuilder_ != null) {
          return fileTaskBuilder_.getMessageOrBuilder();
        } else {
          return fileTask_;
        }
      }
      /**
       * <code>required .FileTask fileTask = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder> 
          getFileTaskFieldBuilder() {
        if (fileTaskBuilder_ == null) {
          fileTaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTask.Builder, cc.changic.platform.etl.base.model.db.proto.FileTaskProto.FileTaskOrBuilder>(
                  getFileTask(),
                  getParentForChildren(),
                  isClean());
          fileTask_ = null;
        }
        return fileTaskBuilder_;
      }

      private cc.changic.platform.etl.base.model.db.proto.JobProto.Job job_ = cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.JobProto.Job, cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder, cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder> jobBuilder_;
      /**
       * <code>required .Job job = 10;</code>
       */
      public boolean hasJob() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.JobProto.Job getJob() {
        if (jobBuilder_ == null) {
          return job_;
        } else {
          return jobBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public Builder setJob(cc.changic.platform.etl.base.model.db.proto.JobProto.Job value) {
        if (jobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          job_ = value;
          onChanged();
        } else {
          jobBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public Builder setJob(
          cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder builderForValue) {
        if (jobBuilder_ == null) {
          job_ = builderForValue.build();
          onChanged();
        } else {
          jobBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public Builder mergeJob(cc.changic.platform.etl.base.model.db.proto.JobProto.Job value) {
        if (jobBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              job_ != cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance()) {
            job_ =
              cc.changic.platform.etl.base.model.db.proto.JobProto.Job.newBuilder(job_).mergeFrom(value).buildPartial();
          } else {
            job_ = value;
          }
          onChanged();
        } else {
          jobBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public Builder clearJob() {
        if (jobBuilder_ == null) {
          job_ = cc.changic.platform.etl.base.model.db.proto.JobProto.Job.getDefaultInstance();
          onChanged();
        } else {
          jobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder getJobBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getJobFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder getJobOrBuilder() {
        if (jobBuilder_ != null) {
          return jobBuilder_.getMessageOrBuilder();
        } else {
          return job_;
        }
      }
      /**
       * <code>required .Job job = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.JobProto.Job, cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder, cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder> 
          getJobFieldBuilder() {
        if (jobBuilder_ == null) {
          jobBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.JobProto.Job, cc.changic.platform.etl.base.model.db.proto.JobProto.Job.Builder, cc.changic.platform.etl.base.model.db.proto.JobProto.JobOrBuilder>(
                  getJob(),
                  getParentForChildren(),
                  isClean());
          job_ = null;
        }
        return jobBuilder_;
      }

      private cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion version_ = cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder> versionBuilder_;
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion getVersion() {
        if (versionBuilder_ == null) {
          return version_;
        } else {
          return versionBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public Builder setVersion(cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion value) {
        if (versionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          version_ = value;
          onChanged();
        } else {
          versionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public Builder setVersion(
          cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder builderForValue) {
        if (versionBuilder_ == null) {
          version_ = builderForValue.build();
          onChanged();
        } else {
          versionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public Builder mergeVersion(cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion value) {
        if (versionBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              version_ != cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance()) {
            version_ =
              cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.newBuilder(version_).mergeFrom(value).buildPartial();
          } else {
            version_ = value;
          }
          onChanged();
        } else {
          versionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public Builder clearVersion() {
        if (versionBuilder_ == null) {
          version_ = cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.getDefaultInstance();
          onChanged();
        } else {
          versionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder getVersionBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      public cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder getVersionOrBuilder() {
        if (versionBuilder_ != null) {
          return versionBuilder_.getMessageOrBuilder();
        } else {
          return version_;
        }
      }
      /**
       * <code>required .ConfigVersion version = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder> 
          getVersionFieldBuilder() {
        if (versionBuilder_ == null) {
          versionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersion.Builder, cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.ConfigVersionOrBuilder>(
                  getVersion(),
                  getParentForChildren(),
                  isClean());
          version_ = null;
        }
        return versionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:FileJob)
    }

    static {
      defaultInstance = new FileJob(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FileJob)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileJob_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileJob_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016file_job.proto\032\014db/app.proto\032\027db/confi" +
      "g_version.proto\032\022db/file_task.proto\032\021db/" +
      "gamezone.proto\032\014db/job.proto\032\023db/ods_con" +
      "fig.proto\"\212\002\n\007FileJob\022\020\n\010fileName\030\001 \001(\t\022" +
      "\021\n\tsourceDir\030\002 \001(\t\022\022\n\nstorageDir\030\003 \001(\t\022\013" +
      "\n\003md5\030\004 \001(\t\022\031\n\021incrementalOffset\030\005 \001(\003\022\021" +
      "\n\003app\030\006 \002(\0132\004.App\022\033\n\010gameZone\030\007 \002(\0132\t.Ga" +
      "meZone\022\035\n\todsConfig\030\010 \001(\0132\n.ODSConfig\022\033\n" +
      "\010fileTask\030\t \002(\0132\t.FileTask\022\021\n\003job\030\n \002(\0132" +
      "\004.Job\022\037\n\007version\030\013 \002(\0132\016.ConfigVersionB0",
      "\n cc.changic.platform.etl.protocolB\014File" +
      "JobProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cc.changic.platform.etl.base.model.db.proto.AppProto.getDescriptor(),
          cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.getDescriptor(),
          cc.changic.platform.etl.base.model.db.proto.FileTaskProto.getDescriptor(),
          cc.changic.platform.etl.base.model.db.proto.GameZoneProto.getDescriptor(),
          cc.changic.platform.etl.base.model.db.proto.JobProto.getDescriptor(),
          cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.getDescriptor(),
        }, assigner);
    internal_static_FileJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FileJob_descriptor,
        new java.lang.String[] { "FileName", "SourceDir", "StorageDir", "Md5", "IncrementalOffset", "App", "GameZone", "OdsConfig", "FileTask", "Job", "Version", });
    cc.changic.platform.etl.base.model.db.proto.AppProto.getDescriptor();
    cc.changic.platform.etl.base.model.db.proto.ConfigVersionProto.getDescriptor();
    cc.changic.platform.etl.base.model.db.proto.FileTaskProto.getDescriptor();
    cc.changic.platform.etl.base.model.db.proto.GameZoneProto.getDescriptor();
    cc.changic.platform.etl.base.model.db.proto.JobProto.getDescriptor();
    cc.changic.platform.etl.base.model.db.proto.ODSConfigProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
