package cc.changic.platform.etl.base.model.db;

import cc.changic.platform.etl.base.model.ExecutableJob;

import java.io.Serializable;

public class App implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_app_config.app_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_app_config.app_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_app_config.db_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String dbUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_app_config.db_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String dbPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_app_config.app_id
     *
     * @return the value of db_etl_server_0001.t_c_app_config.app_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_app_config.app_id
     *
     * @param appId the value for db_etl_server_0001.t_c_app_config.app_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_app_config.app_name
     *
     * @return the value of db_etl_server_0001.t_c_app_config.app_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_app_config.app_name
     *
     * @param appName the value for db_etl_server_0001.t_c_app_config.app_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_app_config.db_user
     *
     * @return the value of db_etl_server_0001.t_c_app_config.db_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_app_config.db_user
     *
     * @param dbUser the value for db_etl_server_0001.t_c_app_config.db_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setDbUser(String dbUser) {
        this.dbUser = dbUser == null ? null : dbUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_app_config.db_pwd
     *
     * @return the value of db_etl_server_0001.t_c_app_config.db_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getDbPwd() {
        return dbPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_app_config.db_pwd
     *
     * @param dbPwd the value for db_etl_server_0001.t_c_app_config.db_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setDbPwd(String dbPwd) {
        this.dbPwd = dbPwd == null ? null : dbPwd.trim();
    }
}