package cc.changic.platform.etl.base.model.db;

import cc.changic.platform.etl.base.annotation.TaskTable;
import cc.changic.platform.etl.base.model.ETLTask;

import java.io.Serializable;

@TaskTable(tableName = "t_c_task_file_task")
public class FileTask extends ETLTask  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.task_type
     *
     * @mbggenerated
     */
    private Short taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.next_interval
     *
     * @mbggenerated
     */
    private Short nextInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.source_dir
     *
     * @mbggenerated
     */
    private String sourceDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.storage_dir
     *
     * @mbggenerated
     */
    private String storageDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.delete_interval
     *
     * @mbggenerated
     */
    private String deleteInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.ods_id
     *
     * @mbggenerated
     */
    private Integer odsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.insert_sql
     *
     * @mbggenerated
     */
    private String insertSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_task_file_task.delete_sql
     *
     * @mbggenerated
     */
    private String deleteSql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.id
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.id
     *
     * @param id the value for db_etl_server_0001.t_c_task_file_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.app_id
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.app_id
     *
     * @param appId the value for db_etl_server_0001.t_c_task_file_task.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.task_name
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.task_name
     *
     * @param taskName the value for db_etl_server_0001.t_c_task_file_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.task_type
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.task_type
     *
     * @mbggenerated
     */
    public Short getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.task_type
     *
     * @param taskType the value for db_etl_server_0001.t_c_task_file_task.task_type
     *
     * @mbggenerated
     */
    public void setTaskType(Short taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.next_interval
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.next_interval
     *
     * @mbggenerated
     */
    public Short getNextInterval() {
        return nextInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.next_interval
     *
     * @param nextInterval the value for db_etl_server_0001.t_c_task_file_task.next_interval
     *
     * @mbggenerated
     */
    public void setNextInterval(Short nextInterval) {
        this.nextInterval = nextInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.source_dir
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.source_dir
     *
     * @mbggenerated
     */
    public String getSourceDir() {
        return sourceDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.source_dir
     *
     * @param sourceDir the value for db_etl_server_0001.t_c_task_file_task.source_dir
     *
     * @mbggenerated
     */
    public void setSourceDir(String sourceDir) {
        this.sourceDir = sourceDir == null ? null : sourceDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.storage_dir
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.storage_dir
     *
     * @mbggenerated
     */
    public String getStorageDir() {
        return storageDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.storage_dir
     *
     * @param storageDir the value for db_etl_server_0001.t_c_task_file_task.storage_dir
     *
     * @mbggenerated
     */
    public void setStorageDir(String storageDir) {
        this.storageDir = storageDir == null ? null : storageDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.file_name
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.file_name
     *
     * @param fileName the value for db_etl_server_0001.t_c_task_file_task.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.delete_interval
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.delete_interval
     *
     * @mbggenerated
     */
    public String getDeleteInterval() {
        return deleteInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.delete_interval
     *
     * @param deleteInterval the value for db_etl_server_0001.t_c_task_file_task.delete_interval
     *
     * @mbggenerated
     */
    public void setDeleteInterval(String deleteInterval) {
        this.deleteInterval = deleteInterval == null ? null : deleteInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.ods_id
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.ods_id
     *
     * @mbggenerated
     */
    public Integer getOdsId() {
        return odsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.ods_id
     *
     * @param odsId the value for db_etl_server_0001.t_c_task_file_task.ods_id
     *
     * @mbggenerated
     */
    public void setOdsId(Integer odsId) {
        this.odsId = odsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.insert_sql
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.insert_sql
     *
     * @mbggenerated
     */
    public String getInsertSql() {
        return insertSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.insert_sql
     *
     * @param insertSql the value for db_etl_server_0001.t_c_task_file_task.insert_sql
     *
     * @mbggenerated
     */
    public void setInsertSql(String insertSql) {
        this.insertSql = insertSql == null ? null : insertSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_task_file_task.delete_sql
     *
     * @return the value of db_etl_server_0001.t_c_task_file_task.delete_sql
     *
     * @mbggenerated
     */
    public String getDeleteSql() {
        return deleteSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_task_file_task.delete_sql
     *
     * @param deleteSql the value for db_etl_server_0001.t_c_task_file_task.delete_sql
     *
     * @mbggenerated
     */
    public void setDeleteSql(String deleteSql) {
        this.deleteSql = deleteSql == null ? null : deleteSql.trim();
    }
}