package cc.changic.platform.etl.base.model.db;

public class GameZone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.app_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.game_zone_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private Integer gameZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.game_zone_name
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private String gameZoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.etl_client_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private String etlClientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.db_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private String dbIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.db_port
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private Short dbPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.timezone
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private Short timezone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_game_zone.site
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    private String site;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.id
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.id
     *
     * @param id the value for db_etl_server_0001.t_c_game_zone.id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.app_id
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.app_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.app_id
     *
     * @param appId the value for db_etl_server_0001.t_c_game_zone.app_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.game_zone_id
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.game_zone_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public Integer getGameZoneId() {
        return gameZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.game_zone_id
     *
     * @param gameZoneId the value for db_etl_server_0001.t_c_game_zone.game_zone_id
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setGameZoneId(Integer gameZoneId) {
        this.gameZoneId = gameZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.game_zone_name
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.game_zone_name
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public String getGameZoneName() {
        return gameZoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.game_zone_name
     *
     * @param gameZoneName the value for db_etl_server_0001.t_c_game_zone.game_zone_name
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setGameZoneName(String gameZoneName) {
        this.gameZoneName = gameZoneName == null ? null : gameZoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.etl_client_ip
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.etl_client_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public String getEtlClientIp() {
        return etlClientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.etl_client_ip
     *
     * @param etlClientIp the value for db_etl_server_0001.t_c_game_zone.etl_client_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setEtlClientIp(String etlClientIp) {
        this.etlClientIp = etlClientIp == null ? null : etlClientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.db_ip
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.db_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public String getDbIp() {
        return dbIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.db_ip
     *
     * @param dbIp the value for db_etl_server_0001.t_c_game_zone.db_ip
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setDbIp(String dbIp) {
        this.dbIp = dbIp == null ? null : dbIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.db_port
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.db_port
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public Short getDbPort() {
        return dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.db_port
     *
     * @param dbPort the value for db_etl_server_0001.t_c_game_zone.db_port
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setDbPort(Short dbPort) {
        this.dbPort = dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.timezone
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.timezone
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public Short getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.timezone
     *
     * @param timezone the value for db_etl_server_0001.t_c_game_zone.timezone
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setTimezone(Short timezone) {
        this.timezone = timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_game_zone.site
     *
     * @return the value of db_etl_server_0001.t_c_game_zone.site
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_game_zone.site
     *
     * @param site the value for db_etl_server_0001.t_c_game_zone.site
     *
     * @mbggenerated Thu Jan 29 21:23:22 CST 2015
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }
}