package cc.changic.platform.etl.base.model.db;

import java.io.Serializable;
import java.util.Date;

public class Job  implements Serializable {

    @Override
    public String toString() {
        return "Job{" +
                "id=" + id +
                ", appId=" + appId +
                ", gameZoneId=" + gameZoneId +
                ", taskTable='" + taskTable + '\'' +
                ", taskId=" + taskId +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.app_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.game_zone_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Integer gameZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.task_table
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private String taskTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.task_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.status
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.modify_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.next_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.last_record_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Date lastRecordTime;

    private String lastRecordTimeStr;

    public String getLastRecordTimeStr() {
        return lastRecordTimeStr;
    }

    public void setLastRecordTimeStr(String lastRecordTimeStr) {
        this.lastRecordTimeStr = lastRecordTimeStr;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.last_record_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Long lastRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.last_record_offset
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private Long lastRecordOffset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job.option_desc
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    private String optionDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.id
     *
     * @return the value of db_etl_server_0001.t_c_job.id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.id
     *
     * @param id the value for db_etl_server_0001.t_c_job.id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.app_id
     *
     * @return the value of db_etl_server_0001.t_c_job.app_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.app_id
     *
     * @param appId the value for db_etl_server_0001.t_c_job.app_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.game_zone_id
     *
     * @return the value of db_etl_server_0001.t_c_job.game_zone_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Integer getGameZoneId() {
        return gameZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.game_zone_id
     *
     * @param gameZoneId the value for db_etl_server_0001.t_c_job.game_zone_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setGameZoneId(Integer gameZoneId) {
        this.gameZoneId = gameZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.task_table
     *
     * @return the value of db_etl_server_0001.t_c_job.task_table
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public String getTaskTable() {
        return taskTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.task_table
     *
     * @param taskTable the value for db_etl_server_0001.t_c_job.task_table
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setTaskTable(String taskTable) {
        this.taskTable = taskTable == null ? null : taskTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.task_id
     *
     * @return the value of db_etl_server_0001.t_c_job.task_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.task_id
     *
     * @param taskId the value for db_etl_server_0001.t_c_job.task_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.status
     *
     * @return the value of db_etl_server_0001.t_c_job.status
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.status
     *
     * @param status the value for db_etl_server_0001.t_c_job.status
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.modify_time
     *
     * @return the value of db_etl_server_0001.t_c_job.modify_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.modify_time
     *
     * @param modifyTime the value for db_etl_server_0001.t_c_job.modify_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.next_time
     *
     * @return the value of db_etl_server_0001.t_c_job.next_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.next_time
     *
     * @param nextTime the value for db_etl_server_0001.t_c_job.next_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.last_record_time
     *
     * @return the value of db_etl_server_0001.t_c_job.last_record_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Date getLastRecordTime() {
        return lastRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.last_record_time
     *
     * @param lastRecordTime the value for db_etl_server_0001.t_c_job.last_record_time
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setLastRecordTime(Date lastRecordTime) {
        this.lastRecordTime = lastRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.last_record_id
     *
     * @return the value of db_etl_server_0001.t_c_job.last_record_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Long getLastRecordId() {
        return lastRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.last_record_id
     *
     * @param lastRecordId the value for db_etl_server_0001.t_c_job.last_record_id
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setLastRecordId(Long lastRecordId) {
        this.lastRecordId = lastRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.last_record_offset
     *
     * @return the value of db_etl_server_0001.t_c_job.last_record_offset
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public Long getLastRecordOffset() {
        return lastRecordOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.last_record_offset
     *
     * @param lastRecordOffset the value for db_etl_server_0001.t_c_job.last_record_offset
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setLastRecordOffset(Long lastRecordOffset) {
        this.lastRecordOffset = lastRecordOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job.option_desc
     *
     * @return the value of db_etl_server_0001.t_c_job.option_desc
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public String getOptionDesc() {
        return optionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job.option_desc
     *
     * @param optionDesc the value for db_etl_server_0001.t_c_job.option_desc
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    public void setOptionDesc(String optionDesc) {
        this.optionDesc = optionDesc == null ? null : optionDesc.trim();
    }
}