package cc.changic.platform.etl.base.model.db;

import java.util.Date;

public class JobLog {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.job_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.status
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.type
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.option_desc
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String optionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_job_log.create_time
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.id
     *
     * @return the value of db_etl_server_0001.t_c_job_log.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.id
     *
     * @param id the value for db_etl_server_0001.t_c_job_log.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.job_id
     *
     * @return the value of db_etl_server_0001.t_c_job_log.job_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.job_id
     *
     * @param jobId the value for db_etl_server_0001.t_c_job_log.job_id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.status
     *
     * @return the value of db_etl_server_0001.t_c_job_log.status
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.status
     *
     * @param status the value for db_etl_server_0001.t_c_job_log.status
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.type
     *
     * @return the value of db_etl_server_0001.t_c_job_log.type
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.type
     *
     * @param type the value for db_etl_server_0001.t_c_job_log.type
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.option_desc
     *
     * @return the value of db_etl_server_0001.t_c_job_log.option_desc
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOptionDesc() {
        return optionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.option_desc
     *
     * @param optionDesc the value for db_etl_server_0001.t_c_job_log.option_desc
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOptionDesc(String optionDesc) {
        this.optionDesc = optionDesc == null ? null : optionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_job_log.create_time
     *
     * @return the value of db_etl_server_0001.t_c_job_log.create_time
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_job_log.create_time
     *
     * @param createTime the value for db_etl_server_0001.t_c_job_log.create_time
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}