package cc.changic.platform.etl.base.model.db;

import java.io.Serializable;

public class ODSConfig  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String odsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_ip
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String odsIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_port
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private Short odsPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_schema
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String odsSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String odsUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_etl_server_0001.t_c_ods_config.ods_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    private String odsPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.id
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.id
     *
     * @param id the value for db_etl_server_0001.t_c_ods_config.id
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_name
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOdsName() {
        return odsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_name
     *
     * @param odsName the value for db_etl_server_0001.t_c_ods_config.ods_name
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsName(String odsName) {
        this.odsName = odsName == null ? null : odsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_ip
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_ip
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOdsIp() {
        return odsIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_ip
     *
     * @param odsIp the value for db_etl_server_0001.t_c_ods_config.ods_ip
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsIp(String odsIp) {
        this.odsIp = odsIp == null ? null : odsIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_port
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_port
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public Short getOdsPort() {
        return odsPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_port
     *
     * @param odsPort the value for db_etl_server_0001.t_c_ods_config.ods_port
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsPort(Short odsPort) {
        this.odsPort = odsPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_schema
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_schema
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOdsSchema() {
        return odsSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_schema
     *
     * @param odsSchema the value for db_etl_server_0001.t_c_ods_config.ods_schema
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsSchema(String odsSchema) {
        this.odsSchema = odsSchema == null ? null : odsSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_user
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOdsUser() {
        return odsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_user
     *
     * @param odsUser the value for db_etl_server_0001.t_c_ods_config.ods_user
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsUser(String odsUser) {
        this.odsUser = odsUser == null ? null : odsUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_etl_server_0001.t_c_ods_config.ods_pwd
     *
     * @return the value of db_etl_server_0001.t_c_ods_config.ods_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public String getOdsPwd() {
        return odsPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_etl_server_0001.t_c_ods_config.ods_pwd
     *
     * @param odsPwd the value for db_etl_server_0001.t_c_ods_config.ods_pwd
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    public void setOdsPwd(String odsPwd) {
        this.odsPwd = odsPwd == null ? null : odsPwd.trim();
    }
}