package cc.changic.platform.etl.base.dao;


import cc.changic.platform.etl.base.model.db.App;

import java.util.List;

public interface AppMapper {

    List<App> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int deleteByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insertSelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    App selectByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_app_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKey(App record);
}