package cc.changic.platform.etl.base.dao;


import cc.changic.platform.etl.base.model.db.JobLog;

public interface JobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insert(JobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insertSelective(JobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    JobLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKeySelective(JobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job_log
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKey(JobLog record);
}