package cc.changic.platform.etl.base.dao;


import cc.changic.platform.etl.base.model.db.Job;

import java.util.List;

public interface JobMapper {

    List<Job> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    Job selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_job
     *
     * @mbggenerated Fri Jan 30 12:10:51 CST 2015
     */
    int updateByPrimaryKey(Job record);
}