package cc.changic.platform.etl.base.dao;


import cc.changic.platform.etl.base.model.db.ODSConfig;

import java.util.List;

public interface ODSConfigMapper {

    List<ODSConfig> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insert(ODSConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int insertSelective(ODSConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    ODSConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKeySelective(ODSConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_ods_config
     *
     * @mbggenerated Thu Jan 29 20:57:34 CST 2015
     */
    int updateByPrimaryKey(ODSConfig record);
}