package cc.changic.platform.etl.base.dao;


import cc.changic.platform.etl.base.model.db.TaskFile;

import java.util.List;

public interface TaskFileMapper {

    List<TaskFile> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    int insert(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    int insertSelective(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    TaskFile selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    int updateByPrimaryKeySelective(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_etl_server_0001.t_c_task_file
     *
     * @mbggenerated Fri Jan 30 12:07:19 CST 2015
     */
    int updateByPrimaryKey(TaskFile record);
}